(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1000,
	height: 230,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.ico04_mov02 = function() {
	this.initialize();

	// レイヤー 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDA9QATgiAKgyIgXgBIgDABIABgTIAVABIAHAAQAEgRgBgHIAAgDIAVACIgFAYQAPAAALgEIABASIgdAEIgKAoQgFAQgNAlgAAAA8QgMgHAAgNQAAgMAMgQIAOAGQgJALABAHQAAANAXAAQASgBATgFIACATIgIABQgVADgKAAQgTAAgKgGgAAAgPQAZgFAUAAIAQABIABATIgVgBQgVgBgUADg");
	this.shape.setTransform(178.7,61.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAaIACAAQAJAAAOgCQAOgEALgHQAKgIABgMQAAgTgaAAQgOAAgbAGIgTAGIgDgUQAEAAANgDQAegGARAAQAcAAAJAQQAHAJAAAMQAAAOgLAMQgLAMgTAGQgKADgWADQgDgKgEgIg");
	this.shape_1.setTransform(163.3,64.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUA+QgJgHAAgMQAAgMAJgHQAKgJAOABIAPABIgCgRQAAgIACgIIATABQgCAIgBAHIACAWQAMAEANAKIAGAFIACACIgJARQgJgLgPgIIAAADQAAAJgGAIQgKAJgRAAQgOAAgKgIgAgLArQAAAKAOgBQARABAAgNIgBgGQgHgDgIABQgOgBgBAMgAhGAlQAJgKAGgPQAHgMAJgYIgZgBIAAgSQAIACAOAAIAHgBQAFgOABgNIAUACIgGAYQAPgBAIgCIABASIgFABIgYACQgFAVgMAYIgOAcgAAQgiIAJgPQAYAJAWANIgJAQQgRgMgdgLg");
	this.shape_2.setTransform(149.4,61.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIAyQgLgLgcgXQgOgLAAgHQABgIAFgFIANgLQAYgSAMgOQAGgFAGgIIASAOIgUASQgNALgXAUQgGAEAAADQAAABAOAKQAYATAZAXIAFADIgRARQgGgIgPgOg");
	this.shape_3.setTransform(134.1,62);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUA+QgJgHAAgMQAAgMAJgHQAKgJANABIAPABIgBgRQAAgIACgIIASABQgCAIAAAHIACAWQALAEAOAKIAGAFIACACIgJARQgKgLgOgIIAAADQAAAJgHAIQgJAJgRAAQgOAAgKgIgAgLArQAAAKAOgBQAQABAAgNIAAgGQgHgDgIABQgPgBAAAMgAhGAlQAIgKAIgPQAIgQAHgUIgZgBIAAgSQAIACANAAIAIgBQAEgOABgNIAVACIgGAYQAPgBAIgCIABASIgFABIgYACQgGAVgLAYIgMAWIgDAGgAAQgiIAJgPQAYAJAWANIgJAQQgRgMgdgLg");
	this.shape_4.setTransform(121.2,61.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhIA6QAIgKAJgTQAIgWAIgWQgTACgLADIgBgTQAQAAASgDQAEgXAAgKIAAgDIAVADIgGAgIAJgBQAOAAAJAJQAHAHAAATQAAAtgNANQgFAHgKAAQgKAAgPgEIABgHIgCgOQAOAGAJAAQAGABADgLQADgOAAgXQAAgJgDgEQgBgEgKAAIgJABIgKAgQgIAVgLAYIgEAHgAAqgKQgIgQgKgLIAQgHQAXAaAKAiIgTAJQgEgUgIgPg");
	this.shape_5.setTransform(106,61.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhHA6QALgSAEgWQADgaAAgtIgBgSIAVABIBWAAIATgBIAAAvIgtgBIAAAPIAqgBIAABSIgRAAIAAgHIg/AAIAAAHIgSAAQABgHAAgMIgBg/IAnABIAAgPIguAAQAAAkgFAXQgFAVgKARQgHgJgIgFgAAbAyIAZAAIAAgRIgZAAgAgLAyIAVAAIAAgRIgVAAgAAbASIAZAAIAAgQIgZAAgAgLASIAVAAIAAgQIgVAAgAgkgnIBbAAIAAgPIhbAAg");
	this.shape_6.setTransform(89.7,62.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhIA9QAJgMAIgTQAJgTAHgYIgdAGIgCgTQANAAAVgDIAEghIAAgCIAVACIgFAaIgBAFIAKgBQANAAAJAJQAHAKAAAQQAAAsgMAPQgHAHgJAAQgJAAgQgFIABgHIgCgNQAOAGAJAAQAHAAACgLQADgMAAgZQAAgIgDgEQgCgFgJAAIgJABIgKAgQgHAVgMAYIgEAIgAAqgHQgGgLgFgHIAQgJQARAYAJAcIgSAJQgEgSgJgQgAAXg3IAMgHQAJAJAGAMIgMAHQgGgNgJgIgAAqhAIAMgGQAJAKAFAKIgMAHQgFgKgJgLg");
	this.shape_7.setTransform(74.2,61.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgBA3IABgRIAAhnIAUAAIgBBoQAQgIAIgKQALgNAFgOQAGAGAJAHQgKAWgQAPQgMALgWAIIgHADgAhJAyQAJgGAIgMQAIgOAEgSQADgQAAgiIgBgOIAWABIgCAkQgBApgMAWQgGAPgQAPQgGgJgKgHg");
	this.shape_8.setTransform(58.5,62.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAqAKIhTAAQgUAAgGABIAAgVIAaABIBTAAIAagBIAAAVQgGgBgUAAg");
	this.shape_9.setTransform(43.6,61.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag9AyQAXgMATgQQALgJAIgNQgSgNgYgOIAPgNIAlAaQATgfAEgUIAVAHIgFALQgQAjgHAKQASANASAUIgQAQQgKgOgWgTQgMAPgLALQgSAPgUAMQgGgKgIgHg");
	this.shape_10.setTransform(27.6,62);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag3AjQgIgVgCg9IAAgKIAWAAQgCAJAAAPQAAAYADARQAFAbAIAAQAEAAADgHQAGgOACgOQAIAIAGAFQgJAtgUAAQgQAAgKgXgAAkgDQgIgVgOgSIAQgIQAeAjAGAxIgTAIQgCgXgJgWg");
	this.shape_11.setTransform(145,29.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhDA9QATgjAKgxIgXAAIgDAAIABgSIAVABIAHAAQADgSAAgHIAAgDIAVACIgEAZQAOgBALgEIABASIgdAFIgLAnQgEAQgOAlgAAAA7QgMgGAAgNQAAgMAMgQIAOAHQgJAKAAAHQAAANAYAAQASAAATgHIABAUIgIABQgTADgLAAQgUAAgJgHgAAAgOQAZgGAUAAIAQAAIABATIgVgBQgWABgTACg");
	this.shape_12.setTransform(129.4,28.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgmA7QgQgKAAgeIAChKIgBgLIAWABIgCAWIgBA4QAAAUAEAGQAGAIAPABQAZgBAMgbQAFgLADgOQAKAHAJADQgIAdgLANQgSATgcAAQgRABgLgIg");
	this.shape_13.setTransform(114.9,29);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhKA1QATgLANgPQAUgUAIgZQAEgQABgQIgjAAIAAgTIAoABIANgBIgBAKQAAAiARAcQAMATAOAMQALAKANAHQgIAHgGALQgWgPgRgWQgIgLgGgNQgEgIgEgNQgGAZgPAWQgQAUgYAQQgEgKgJgHg");
	this.shape_14.setTransform(100.2,29.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGBKQgCgJgDgHIASABQAGAAAAgEIAAgJIgxAAQAIAGALAKIgNALQgJgKgOgKIAKgHIgUAAIgTABIAAgPIBfAAIAAgFIgSAAQgWAAgLgCQgLgEgFgIQgJAHgPAIIgHgQQAJgDAOgJIAAgRIgUABIAAgQIANABIAYgBIgBAgQAEAIAIADQAIADAUAAQAwAAAUgDQgEAIgBAHIgbABIAAAFIAcAAIAAAPIgTgBIgJAAIAAAPQAAAIgFADQgFACgOAAgAgWAIIAAgzIAbABIACgEIgmAAIAAgPIAXABIgHgLIAPgCIAIANIAQAAQAEgFAEgIIASADIgHAKIAagBIAAAPIgsAAIgCAEIAkgBIgBANIABAmgAgGgBIAwAAIAAgFIgwAAgAgGgOIAwAAIAAgEIgwAAgAgGgaIAwAAIAAgFIgwAAgAhFg8IALgLQALAHAOAOIgLANQgMgOgNgJg");
	this.shape_15.setTransform(84.3,28.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXA+QgMgFAAgPQAAgLAHgHQAKgNAWgJQAAgHgHAAQgOAAgTAPQgIAGgGAIIgPgOQAGgFAJgHQAKgMAJgQIABgCIgeAAIABgSQAIACAdAAQAGgNAAgHIATACIgEAPIgCACIAIAAQAdgCANgEIACASIgNABQgUADgaABQgHANgIAIIAAAAIADgCQAKgHAMAAQASAAAEARIAYgJIAMgFIAIARIgSAEIgYAJIAAABIAAANIAAAFIAAAIIgSABIABgWIgOAIQgIAGAAAHQAAAMAZAAQAdAAASgHIACAVIgIABQgXACgSAAQgWABgLgIg");
	this.shape_16.setTransform(68.1,28.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgfA5QgJgFgFgNQgDgFAAgIIAXgCQAAAJAFAFQAGAKAOAAQANAAAGgGQAIgFgBgJQABgKgJgFQgFgCgVgGQgOgDgKgEQgMgKAAgQQAAgRAMgKQANgKATAAQAbAAAMARQAFAGADAMIgXACQgBgHgEgEQgGgHgNgBQgJAAgHAGQgGAEAAAIQAAAKALAFIAUAFQATAEAHAFQAOAJAAASQAAARgKAKQgNAMgaAAQgTAAgMgJg");
	this.shape_17.setTransform(55.5,28.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAtA/IABgXIABhMQgDANgEALIgYA2QgGANgBAIIgRAAQgBgEgGgRIgXg1QgEgJgEgQIABBMQAAAOABAJIgWAAQABgJAAgOIAAhPQAAgNgBgKIAdAAQACAJAEAKIAfBNIAghNQADgJADgKIAdAAQgBALAAAMIAABPQAAAOABAJg");
	this.shape_18.setTransform(41.9,28.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglAyQgSgRAAghQAAgfATgTQAQgPAVAAQASAAAOAIQAKAHAHAKIAEANIgWAFQgDgJgEgFQgHgKgQAAQgPAAgKANQgKAMAAAVQAAAVALANQAJANAPAAQARAAAJgMQAEgGABgJIAXAEQgEAQgHAIQgNASgfAAQgYAAgOgQg");
	this.shape_19.setTransform(27.7,28.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAFAFAAAGQAAAHgFAFQgGAGgHgBQgGABgFgGg");
	this.shape_20.setTransform(13.6,67.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgEQgEgFAAgGIgMhOQgBgJAHgHQAIgIAMAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAg");
	this.shape_21.setTransform(13.6,58.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAFAFAAAGQAAAHgFAFQgGAGgHAAQgGAAgFgGg");
	this.shape_22.setTransform(13.6,36.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgFQgEgEAAgHIgMhNQgBgJAHgHQAIgIAMAAQANAAAIAIQAIAIgCAIIgMBNQAAAHgEAEQgFAFgGAAg");
	this.shape_23.setTransform(13.6,28.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F44336").s().p("AgMAMQgFgFAAgHQAAgGAFgFQAGgFAGAAQAHAAAFAFQAGAFAAAGQAAAHgGAFQgFAGgHgBQgGABgGgGg");
	this.shape_24.setTransform(13.4,67.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F44336").s().p("AgKA3QgEgFAAgGIgMhOQgBgJAHgHQAJgIALAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAQgFAAgFgEg");
	this.shape_25.setTransform(13.4,58.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F44336").s().p("AgMAMQgFgFAAgHQAAgGAFgFQAGgFAGgBQAHABAFAFQAGAFAAAGQAAAHgGAFQgFAGgHAAQgGAAgGgGg");
	this.shape_26.setTransform(13.4,36.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F44336").s().p("AgKA2QgEgEAAgHIgMhNQgBgJAHgHQAJgIALAAQANAAAIAIQAIAHgCAJIgMBNQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_27.setTransform(13.4,28.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F44336").s().p("AiMFuItVAAQhIAAgygzQgzgyAAhIIAAo5QAAhHAzgzQAygyBIAAIfDAAQBIAAAzAyQAyAzAABHIAAI5QAABIgyAyQgzAzhIAAItXAAIiNC3g");
	this.shape_28.setTransform(116.8,55);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#B0BEC5").s().p("AgtARIAAghIBaAAIAAAhg");
	this.shape_29.setTransform(122.3,156.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#B0BEC5").s().p("AhTA4ICAg4IAAAAIiAg3IAAglICnBNIAAAfIinBNg");
	this.shape_30.setTransform(101.3,156.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#B0BEC5").s().p("Ak5E6QgWAAgPgPQgQgPAAgWIAAoLQAAgVAQgQQAPgPAWAAIJzAAQAWAAAPAPQAQAQAAAVIAAILQAAAVgQAQQgPAPgWAAgAk5EGIJzAAIAAm7IpzAAgAjWkKQgIAIAAALQAAAKAIAIQAIAIALAAQALAAAHgIQAIgIAAgKQAAgLgIgIQgHgIgLAAQgLAAgIAIgAklkKQgHAIAAALQAAAKAHAIQAIAIALAAQALAAAIgIQAHgIAAgKQAAgLgHgIQgIgIgLAAQgLAAgIAIg");
	this.shape_31.setTransform(117.1,162.7);

	this.addChild(this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,233.6,194.2);


(lib.ico03_mov02 = function() {
	this.initialize();

	// レイヤー 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3AiQgJgWgBg7IAAgKIAVAAIgBAYQAAAdADAMQAEAbAJAAQAEAAADgHQAGgOACgOQAHAIAHAFQgEAYgHALQgIAKgKAAQgQAAgKgYgAAkgDQgHgTgQgUIARgIQAeAkAGAwIgUAHQgBgYgJgUg");
	this.shape.setTransform(198.3,62.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA+QgJgHAAgMQAAgMAJgHQAKgJANABIAPABIgBgRQAAgIACgIIASABQgCAIAAAHIACAWQALAEAOAKIAIAHIgJARQgKgLgOgIIAAADQAAAJgHAIQgJAJgRAAQgOAAgKgIgAgLArQAAAKAOgBQAQABAAgNIAAgGQgHgDgIABQgPgBAAAMgAhGAlQAIgKAIgPQAIgQAHgUIgZgBIAAgSIAVACIAIgBQAEgOABgNIAVACIgGAYQAPgBAIgCIABASIgFABIgYACQgGAVgLAYIgPAcgAAQgiIAKgPQAXAJAWANIgJAQQgSgMgcgLg");
	this.shape_1.setTransform(182.7,61.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoA+QgBgLgCgKQAWAJAVgBQAPAAAKgGQAMgHAAgJQAAgSgbAAQgWAAgRAMIgHAHIgUgBIAJhAIAUACQgEAMgDAZIgBAFIABAAQAGgGAOgDQANgEANAAQAVAAAMAIQAMAJAAAPQAAATgRAMQgOAKgaAAQgSABgWgGgAgigyIAJgRQAIAFASAFQASAGAOACIgGASQgkgHgZgMg");
	this.shape_2.setTransform(167.5,61.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhIA6QAHgIAKgVQAJgVAGgXQgTADgJACIgCgTQARAAARgDQAEgaAAgHIAAgDIAVADIgGAgIAKgBQAOAAAHAJQAIAHAAATQAAAtgMANQgGAHgKAAQgKAAgPgEIABgHIgCgOQAOAGAJAAQAHABACgLQADgQAAgVQAAgJgDgEQgCgEgJAAIgKABQgEARgFAPQgIAWgMAXIgCAFIgBACgAAqgKQgHgPgMgMIARgHQAXAaAKAiIgSAJQgEgTgJgQg");
	this.shape_3.setTransform(153.3,61.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqBFQABgFAAgVIABgXIgBAAIgHAHQgIAJgEAFIgJgSIAdgYIAAgXIgYADIgBgSIAagBIAAgcIAVABIgCAOIgBALIADgBIAGAHQgCABgIAJIAAALIAAAAIAEgDQAWgSAXAAQASABAMANQANAMAAASQAAAPgHAMQgHANgLAFQgNAHgQgBQgNAAgJgDQAAgLgDgKQAMAHAPAAQAOgBAJgJQAJgJAAgPQAAgLgHgHQgIgIgNAAQgTAAgZAXIAAAQQAAAmABAKg");
	this.shape_4.setTransform(137.5,62);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhIA9QAHgJAKgWQAJgTAGgYIgcAGIgCgTQAOAAAUgDQAEgaAAgHIAAgCIAVACIgGAfIAKgBQAOAAAHAJQAIAJAAARQAAAtgMAOQgHAHgJAAQgKAAgPgFIABgHIgCgNQAOAGAJAAQAHAAACgLQADgPAAgWQAAgIgDgEQgCgFgJAAIgKABQgEARgFAPQgIAWgMAXIgCAGIgBACgAAqgHQgFgKgGgIIAQgJQARAYAJAcIgSAJQgFgSgIgQgAAXg3IAMgHQAJAJAGAMIgMAHQgIgOgHgHgAAphAIANgGQAJAKAFAKIgMAHQgGgLgJgKg");
	this.shape_5.setTransform(122,61.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBJQgCgIgDgIIAUACQAHAAAAgEIAAgIIg2ABIAAgPIA2ABIAAgHIguAAIgSABIAAgQIARABIAvAAIAAgHIg1ABIAAgMIA1ABIAAgHIgwABIAAghIAwABIAAgGIgsAAIgTABIAAgQIAUABIArAAIgBgLIARAAIgBALIAtAAIATgBIAAAQIgSgBIguAAIAAAGIAxgBIAAAhIgxgBIAAAHIA1gBIgBASIAOgBIAAAQIgOgBIAAAJIABARIgSAAIAAgGIgjAAIAAAJQAAALgFADQgCAEgPAAgAAHAiIAjAAIAAgHIgjAAgAAHANIAjAAIAAgHIgjAAgAAHgXIAgAAIAAgHIggAAgAgmgXIAeAAIAAgHIgeAAg");
	this.shape_6.setTransform(106.3,62);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEArQATgDAKgFQAXgNAAgZQAAgYgUgLQgIgFgIgBQgEAngKAZQgPAegSAAQgOAAgIgNQgKgMABgTQAAgaARgTQAVgWAggBQAdAAARARQASAQAAAbQAAATgLAQQgKAPgSAHQgJAFgQACQgDgJgFgKgAgagkQgKAIgGALQgGAMAAALQAAAJADAIQAEAGAFAAQAJAAAIgVQAKgSAEgiQgMACgJAGg");
	this.shape_7.setTransform(90.3,62.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAqAKIhTAAQgTAAgHABIAAgVIAaABIBTAAIAagBIAAAVQgGgBgUAAg");
	this.shape_8.setTransform(74.9,61.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAcAQQgLgYgFghIgCgMIAUgDQAAALAHAaQAKAoAZAbQgJAGgIAIQgQgSgLgcgAhLAxQANgNAKgVQALgXAEgeIACgQIAAgCIAWADIgDANQgEAhgIAUQgKAbgTAWQgJgJgJgEgAAjgxIAMgGQAHAMAFALIgMAFQgFgLgHgLgAA1g4IALgGQAIALAEALIgMAFQgFgNgGgIg");
	this.shape_9.setTransform(59.5,61.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAqAKIhTAAQgUAAgGABIAAgVIAaABIBTAAIAagBIAAAVQgGgBgUAAg");
	this.shape_10.setTransform(44.4,61.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaAzQAVgGAHgJQAPgNACgXIABgTIgnAAIAAAkIgVAAIABgkIgKAAIgUABIAAgTIAVABIAJAAIgBgfIAVAAIAAAfIAnAAIAAgfIAUAAIgBAfIALAAIAUgBIAAATIgUgBIgLAAIgBAZQgDAdgUARQgMAJgRAHQgEgIgIgJg");
	this.shape_11.setTransform(28.4,62);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag3AjQgJgYgBg6IAAgKIAWAAQgCAJAAAPQAAAYADARQAFAbAIAAQAEAAADgHQAGgOACgOQAIAIAGAFQgJAtgUAAQgQAAgKgXgAAkgDQgIgVgOgSIAQgIQAeAjAGAxIgTAIQgCgXgJgWg");
	this.shape_12.setTransform(194.7,29.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhCA9QASgjAKgxIgXAAIgDAAIABgSIAVABIAHAAQADgQAAgJIAAgDIAVACIgEAZQAOgBALgEIABASIgdAFIgKAnQgFAQgNAlgAAAA7QgMgGAAgNQAAgMAMgQIAOAHQgIAKAAAHQAAANAYAAQARAAATgHIABAUIgHABQgUADgKAAQgUAAgKgHgAAAgOQAZgGAUAAIAQAAIABATIgVgBQgWABgTACg");
	this.shape_13.setTransform(179.1,28.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfAzQAVgCAMgHQAbgOAAghQAAgkgWAAQgHAAgIAIQgUAWAAAcIAAADIgTABIgBgXQAAgTACgXIADgZIAVABQgDAHgDAYIgCAQIAAAAIABgEQADgIAHgLQANgQAQAAQAQAAALAPQAMAQAAAbQAAAsgqATQgMAGgRADQgEgLgFgIg");
	this.shape_14.setTransform(164.2,28.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAIBKIABgTIAAhYIgDAAQgHAUgRARQgEgFgIgIQAQgQALgZQAFgPAAgIIATAFIgEAJIgEALIAsAAIARgCIAAASIgRgBIgfAAIAAAVIAqgCIAAAQIgQgBIgaAAIAAAVIAaAAIARgCIAAASIgRgBIgaAAIAAASQAAANABAGgAgzBKIABgUIABg+IgPAQQgEgIgFgIQASgRAMgcQAFgLACgJIASAGIgPAiIAABXQAAALACAJg");
	this.shape_15.setTransform(150.1,28.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXA+QgMgGAAgOQAAgKAHgIQALgNAVgJQgBgHgGAAQgOAAgTAPQgIAGgGAIIgPgOQAIgGAHgGQAOgSAFgKIABgCIgdAAIAAgSQAIACAdAAQAFgNACgHIATACIgFAPIgCACIAIAAQAcgCAPgEIABASIgNABQgVADgaABQgGANgIAIIAAAAIADgCQAKgHAMAAQASAAAEARIAkgOIAIARQgHAAgLAEIgYAJIAAAbIgSABIABgWIgNAIQgJAGAAAHQAAAMAZAAQAeAAARgHIACAVIgIABQgWACgSAAQgXABgLgIg");
	this.shape_16.setTransform(134.2,28.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AguBEIACgSIAAhlQAAgMgCgEIAXAAIgBAuQAeALApAVIgLATQgVgNgjgRIgEgBIABBFg");
	this.shape_17.setTransform(119.9,29);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AABBEIAAhHQgWAMghAMQgEgKgHgJQAvgKAkgdQAWgSAHgMIASANIgGAFQgRASgUAPIAABUg");
	this.shape_18.setTransform(106,28.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbAzQAVgGAJgJQAPgNACgYIAAgSIgoAAIABAjIgVAAIABgjIgKAAIgUABIAAgTIAVAAIAJAAIgBgeIAVAAIgBAeIAoAAIAAgdIAUAAIAAAdIAJAAIAVAAIAAATIgUgBIgLAAQAAATgBAGQgEAdgTARQgLAJgSAHQgFgIgIgJg");
	this.shape_19.setTransform(91.4,29);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNA3QANgHAJgLQAMgNAAgeIgBgKIgsAAIAAgSQAKACARAAIARgBIgCgjIAUgBIAAAGIABAcQAPgCAJgEIABATIgZAFIAAAHQAAAYgDAMQgEAUgOAMQgIAGgKAGQgEgJgJgGgAg6A4QgFgYAAgcQAAgTAGgoIABgLIAVACQgDAJgCAKQgDAPAAARIgCAQIABAFIAAAVQAEgOAGgMIAPAHQgTAhABASIgTABg");
	this.shape_20.setTransform(76.9,29.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhBBJIABgSIgBhoIAuABQAGgNADgLIASACIgIAWIBCgBIgBAQIAABYQAAALgGAEQgFACgNAAIgRgBQgBgHgDgKIAUABIAGAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAhTIheAAIAABXIABASgAggAwIABg2IgBgMIBAAAIgBArIABAMIguAAIAAALgAgOAVIAcAAIAAgXIgcAAg");
	this.shape_21.setTransform(61.3,28.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAUBKIABgVIAAgyQgMgJgHgMQgFAcgPAXQgQAXgYASQgGgKgHgFQAKgGAJgIQARgQAIgOQgHgIgNgJIAKgMQAJAHAIAHQAGgLAFgZIgYAAQgLAbgUAUQgDgIgHgFQATgUAKgdQAEgMABgKIASAEIgFASIAiAAIgCAKQAFAMALAMIAAgkIgBgSIATAAIgBASIAAA0IAQAHQAMAIAJAEQgFAHgEAKQgRgJgLgIIABA4g");
	this.shape_22.setTransform(45.6,29);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhHA9IADgEQAJgQAIgcIAPALQgGAUgIARIgGANgAASBIQAAgKgDgGQAIACAIAAQAEAAACgCQABAAABgGIg0AAIgDAMIgRgBQAFgQAFgeIgCAAIgNABIAAgQIARAAIACgYIgKALQgEgGgIgHQAMgLAIgOQAIgNABgJIARADIgFANIAxAAIAXgCIAAASIgVgBIg6AAIgHAMIBMgBIgBAfIAOAAIAAAQIgNgBIgCAAIgCATIAMAAIAAARIgOgBQgCAPgEAFQgFADgMAAgAAWAiIAUAAIACgTIgTAAgAgKAiIARAAIACgTIgQAAgAAaAAIATAAIAAgQIgSAAgAgFAAIAQAAIABgQIgQAAgAhKgSIALgMQAPAKALALIgLAKQgMgKgOgJgAhDg7IAMgLQANAKALAKIgMAOQgLgNgNgKg");
	this.shape_23.setTransform(29.2,28.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAFAFAAAGQAAAHgFAFQgGAGgHgBQgGABgFgGg");
	this.shape_24.setTransform(13.6,67.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgEQgEgFAAgGIgMhOQgBgJAHgHQAIgIAMAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAg");
	this.shape_25.setTransform(13.6,58.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAFAFAAAGQAAAHgFAFQgGAGgHAAQgGAAgFgGg");
	this.shape_26.setTransform(13.6,36.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgFQgEgEAAgHIgMhNQgBgJAHgHQAIgIAMAAQANAAAIAIQAIAIgCAIIgMBNQAAAHgEAEQgFAFgGAAg");
	this.shape_27.setTransform(13.6,28.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F44336").s().p("AgMAMQgFgFAAgHQAAgGAFgFQAGgFAGAAQAHAAAFAFQAGAFAAAGQAAAHgGAFQgFAGgHgBQgGABgGgGg");
	this.shape_28.setTransform(13.4,67.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F44336").s().p("AgKA3QgEgFAAgGIgMhOQgBgJAHgHQAJgIALAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAQgFAAgFgEg");
	this.shape_29.setTransform(13.4,58.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F44336").s().p("AgMAMQgFgFAAgHQAAgGAFgFQAGgFAGgBQAHABAFAFQAGAFAAAGQAAAHgGAFQgFAGgHAAQgGAAgGgGg");
	this.shape_30.setTransform(13.4,36.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F44336").s().p("AgKA2QgEgEAAgHIgMhNQgBgJAHgHQAJgIALAAQANAAAIAIQAIAHgCAJIgMBNQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_31.setTransform(13.4,28.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F44336").s().p("AiMFuItVAAQhIAAgygzQgzgyAAhIIAAo5QAAhHAzgzQAygyBIAAIfDAAQBIAAAzAyQAyAzAABHIAAI5QAABIgyAyQgzAzhIAAItXAAIiNC3g");
	this.shape_32.setTransform(116.8,55);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#B0BEC5").s().p("AiLEpQhMg7ghhaIguAAQgbgBgTgSQgSgSAAgbIAAhGQAAgPAJgQQAJgPAPgIQABiWBVhQQBWhQCZAAQCaAABVBQQBXBRAACVQAPAIAKAPQAIAQABAPIAABGQAAAbgTASQgTASgaABIguAAQgiBahNA7QhGA3hFgBQhEABhHg3gAhWEWQAwAdAmAAQBFAABHhGQBVhTAAh3IgCgtQgWgTgmgOQgmgPgwgEQAPAPAGAXQgLgJhGgXQg8gVgigoIgJgLIgLgQQgDgEgBAGQgBA7gkAsQgjAogxAHIgBAbQAAAxAPArQArA0BnAHQAIgMAOgHQAQgHATAAQAXgBATANQASANAAATQAAARgSANQgTAOgXAAQgUgBgQgHQgPgIgHgMQhEgFgsgUQAjA0A2AfgADOi/QArA3AOBZIAZAAQgDiDhKhDQhJhEiKAAQiJAAhJBEQhKBDgCCDIAYAAQANhZAsg3QBFhYCIAAQCJAABFBYgABDA9QgLgLAAgQQAAgOALgMQALgJAPABQAQgBAKAJQALAMAAAOQAAAQgLALQgKALgQgBQgPABgLgLgAh2A9QgLgLAAgQQAAgOALgMQALgJAPABQAPgBALAJQALAMAAAOQAAAQgLALQgLALgPgBQgPABgLgLg");
	this.shape_33.setTransform(117.3,163.5);

	this.addChild(this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,233.6,198.7);


(lib.ico02_mov02 = function() {
	this.initialize();

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgiBHQAAgJgEgIQAPACALAAQAGAAAAgGIAAgaIhAABIAAgSIAUABIAsAAIAAgSIgjAAIgUACIAAgSIA3ABIAAgTQgZACgZABIgFgRIAHAAQAqAAAcgGQATgDALgEIANAQQgYAGgZADIAAAVIA1gBIAAASIgTgCIgiAAIAAASIApAAIAUgBIAAASIg9gBIAAAgQAAALgGACQgEADgMAAg");
	this.shape.setTransform(85.1,61.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAkBJIAAgIIhGAAIAAAIIgSAAIAAg9IAsABIAAgNIgqAAIgUAAIAAgRIAUABIAqAAIgBgTIARAAIgBATIAtAAIAUgBIAAARIgUAAIgtAAIAAANIAwgBIgBAPIABAugAgiAxIBHAAIAAgUIhHAAgAAPgeIABgMIggAAIABAMIgSAAIAAgMIglABIAAgSIASABIATAAIAAgOIASAAIgBAOIAgAAIgBgOIASAAIgBAOIAVAAIATgBIAAASIgogBIABAMg");
	this.shape_1.setTransform(69.2,62);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhIA9QAJgLAIgUQAIgQAHgbIgcAGIgCgTQANAAAVgDQAEgXAAgKIAAgCIAVACIgCAEIgEAbIAKgBQANAAAJAJQAHAJAAARQAAAtgNAOQgGAHgJAAQgKAAgPgFIAAgHIgBgNQAOAGAKAAQAFAAADgLQADgNAAgYQAAgIgDgEQgCgFgJAAIgJABIgLAgQgIAZgLAUIgDAIgAAqgHQgHgOgFgEIARgJQASAZAIAbIgTAJQgDgSgJgQgAAXg3IAMgHQAJAKAHALIgNAHQgHgMgIgJgAAqhAIALgGQAJAJAHALIgNAHQgGgKgIgLg");
	this.shape_2.setTransform(53.2,61.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglAyQgSgSAAggQAAgfATgTQAPgPAXAAQASAAANAIQAKAGAGALIAFANIgVAFQgEgJgDgFQgJgKgPAAQgPAAgKANQgKAMAAAVQAAAVAKANQAKANAPAAQASAAAIgMQAEgEACgLIAWAEQgFARgGAHQgNASgeAAQgYAAgPgQg");
	this.shape_3.setTransform(39.1,61.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgwA/QACgJAAgLIAAhVIgCgVIA0ABQAXAAALALQAKALAAARQAAARgLALQgLALgXAAIgcAAIAAAbQAAAMABAIgAgZgBIAcAAQAYAAAAgVQgBgJgFgHQgFgFgNgBIgcAAg");
	this.shape_4.setTransform(27.4,61.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag3AjQgJgYgBg6IgBgKIAXAAIgCAYQABAdADAMQAEAbAIAAQAEAAADgHQAGgLADgRQAGAIAIAFQgFAYgHAKQgIALgKAAQgPAAgLgXgAAlgDQgIgTgQgUIARgIQAdAjAHAxIgTAIQgCgYgIgVg");
	this.shape_5.setTransform(221.1,29.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgTA/QgKgIAAgMQAAgMAKgIQAJgHAOgBIAOACIgBgRQABgIABgHIASABQgCAHAAAHIACAVQAMAFANAKIAGAEIACACIgJASQgKgLgOgJIAAAEQAAAJgGAIQgLAJgQAAQgOAAgJgHgAgKAqQAAAKANAAQAQAAAAgNIAAgFQgHgCgHgBQgPABAAAKgAhGAlQAIgJAIgQQAGgMAJgYIgZAAIAAgSQAIABANAAIAIAAQAFgPABgNIAUACIgGAZQAPgCAIgDIABASIgFABIgXAEQgHAUgLAYIgPAcgAAQghIAJgQQAYAJAWAMIgJARQgRgMgdgKg");
	this.shape_6.setTransform(205.5,28.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoA+QgBgOgCgGQAXAHAUABQAPAAAKgHQALgGAAgLQAAgRgbAAQgVAAgRAMQgDACgEAFIgUgBIAJg/IAUABQgDAJgFAcIAAAFIAAAAQAHgHAOgCQANgEANAAQAUAAAMAHQANAKAAAPQAAATgQAMQgPALgaAAQgTAAgVgGgAgjgzIAKgQQAJAFAQAGQATAFAOACIgHASQgjgHgagNg");
	this.shape_7.setTransform(190.3,28.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhIA7QAIgMAJgTQAHgQAIgbQgUADgIACIgCgTQARAAARgDQAEgYAAgIIAAgEIAVADIgGAfIAKAAQAOAAAHAJQAIAIAAASQAAAsgMAOQgGAIgKgBQgKAAgPgEIAAgIQAAgGgBgHQAOAHAJgBQAGAAADgLQADgNAAgXQAAgJgDgEQgCgEgJAAIgKAAQgEASgFAPQgKAagKATIgDAIgAAqgJQgJgRgKgKIARgIQAXAaAKAiIgTAJQgEgUgIgOg");
	this.shape_8.setTransform(176.1,28.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgpBFIABgZIAAgYIgHAIQgJAIgEAFIgJgTQAEgCAZgVIABgXIgYACIgBgSIAaAAIAAgcIAUAAIgBAQIgBAKIACgBIAGAHIgJAKIgBALIAFgDQAVgRAWAAQAUAAAMAMQAMAMAAAUQAAAPgHAMQgGALgNAHQgLAFgRAAQgNABgJgEQAAgLgCgJQALAFAPAAQAPAAAJgJQAIgKABgOQAAgLgIgHQgHgIgNABQgUgBgZAWIACBBg");
	this.shape_9.setTransform(160.3,29);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAJAyQgMgMgcgWQgNgKAAgIQAAgHAFgGIAOgMQAXgRAMgNQAIgJADgFIATAPIgUARQgOANgWARQgGAFAAADQAAABAOAJQAYAUAZAXIAEADIgQARQgGgIgOgOg");
	this.shape_10.setTransform(145.4,29);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag5A4QgDgHAAgHQgBgNALgIQAMgIARAAQAKAAAFACIAAgCQgCgWAAgtIgCgPIAUAAIgBAjQAfABAQgGIABAUIgKABQgNABgZABIACAiQALADAOAHIAaARIgNASIgLgKQgMgJgJgEIgGgDIAAAFQAAAbgiABQgYAAgKgOgAgjAiQgGADAAAFQAAAFAGADQAEACAIABQAJgBAFgEQADgCABgGIgBgIQgIgCgHAAQgJAAgFAEg");
	this.shape_11.setTransform(132.5,28.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag9A9QgFgcAAgXQAAgUADgUIAGgjIAAgBIAWADQgFAKgEAZQgEAYAAATIAAALIAAADIAAAAIACgFIAHgRIANAGQgQAfAAARIABAFIgUABgAgRA7QgJgHAAgMQAAgMAJgIQAJgHANAAQAHAAAHADIgBghIghAAIgEAAIgGAAIABgTQAJADASgBIAOAAIAAgfIAUgBQgBAEAAATIAAAIIAVgEIAEgBIABgBIABASIgbAFIABAmQANAFAMAJIAFADIgIATQgFgGgHgEIgKgGIAAACQAAAGgBADQgGAPgZAAQgNAAgJgHgAgJAoQAAAKANAAQAKgBADgFQACgCAAgGIAAgEQgIgDgFAAQgPAAAAALg");
	this.shape_12.setTransform(118.7,28.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeBJQgCgKgDgGIAUACQAHAAAAgEIAAgIIg2ABIAAgPIA2ABIAAgHIguAAIgSABIAAgQIARABIAvAAIAAgHIg1ABIAAgMIA1ABIAAgHIgwABIAAghIAwABIAAgGIgsAAIgTABIAAgQIAUABIArAAIgBgLIARAAIgBALIAtAAIATgBIAAAQIgSgBIguAAIAAAGIAxgBIAAAhIgxgBIAAAHIA1gBIgBASIAOgBIAAAQIgOgBIAAAJIABARIgSAAIAAgGIgjAAIAAAJQAAALgFADQgCAEgPAAgAAHAiIAjAAIAAgHIgjAAgAAHANIAjAAIAAgHIgjAAgAAHgXIAgAAIAAgHIggAAgAgmgXIAeAAIAAgHIgeAAg");
	this.shape_13.setTransform(102.8,29);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEArQATgDAKgFQAXgNAAgZQAAgYgUgMQgIgEgIAAQgEAlgKAaQgOAegTAAQgOAAgIgMQgKgNABgUQAAgYARgUQAVgWAgAAQAdAAARAQQASAQAAAbQAAASgLAQQgKAQgSAIQgKADgPAEQgDgKgFgKgAgagkQgKAIgGALQgGAMAAAKQAAALADAGQAEAHAFAAQAJAAAIgUQAKgUAEggQgMABgJAGg");
	this.shape_14.setTransform(86.8,29.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AArAwIgGABQgcAFg8AGIgPACIgDgVIASgBQAKgWANgoQAKggACgNIAVAFIgEALQgQA5gOAhQAngEAagEIgIgPQgHgNgIgKIASgHQAYAfAPApIgTAKIgIgUg");
	this.shape_15.setTransform(71.4,28.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag0AwQAcgIAKgSQAGgLABgSIgnAAIgUABIAAgTIAUABIBcAAIAVgBIAAATIgVgBIghAAQgCAZgKARQgKATgdAMQgFgIgJgKgAgyguIAAgTQAJABAMAAIA7AAQAMAAAJgBIAAATg");
	this.shape_16.setTransform(57.4,29.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAEAPQgYAdgjARQgFgKgIgIQAPgGARgMQAkgZAQgmIACgDIgzABIgSAAIAAgUIAOABIA6AAQAKgBAEgBIALALIgFAIQgMAbgNAPQASANALAKIAYAXIgQARQgVgcgcgUg");
	this.shape_17.setTransform(42.3,29.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag9AsQAWgBAZgKQAagKASgXQAKgNAIgWQAJAJAIAFQgKAXgOAQQgeAig3ALIgLACgAhAgKIALgQQAYALASALIgKAQQgTgMgYgKgAg0gxIALgQQAZAKAQALIgJASQgWgPgVgIg");
	this.shape_18.setTransform(28.3,29);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAFAFAAAGQAAAHgFAFQgGAGgHgBQgGABgFgGg");
	this.shape_19.setTransform(13.7,67.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgEQgEgFAAgGIgMhOQgBgJAHgHQAIgIAMAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAg");
	this.shape_20.setTransform(13.7,58.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAFAFAAAGQAAAHgFAFQgGAGgHAAQgGAAgFgGg");
	this.shape_21.setTransform(13.7,36.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgFQgEgEAAgHIgMhNQgBgJAHgHQAIgIAMAAQANAAAIAIQAHAIgBAIIgMBNQAAAHgEAEQgFAFgGAAg");
	this.shape_22.setTransform(13.7,28.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F44336").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAEAFAAAGQAAAHgEAFQgGAGgHgBQgGABgFgGg");
	this.shape_23.setTransform(13.5,67.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F44336").s().p("AgKA3QgEgFAAgGIgMhOQgBgJAHgHQAJgIALAAQANAAAIAIQAIAIgCAIIgMBOQAAAGgEAFQgFAEgGAAQgFAAgFgEg");
	this.shape_24.setTransform(13.5,58.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F44336").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAEAFAAAGQAAAHgEAFQgGAGgHAAQgGAAgFgGg");
	this.shape_25.setTransform(13.5,36.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F44336").s().p("AgKA2QgEgEAAgHIgMhNQgBgJAHgHQAJgIALAAQANAAAIAIQAIAHgCAJIgMBNQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_26.setTransform(13.5,28.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F44336").s().p("AiMFuItVAAQhIAAgygzQg0gyAAhIIAAo5QAAhHA0gzQAygyBIAAIfDAAQBIAAAzAyQAzAzAABHIAAI5QAABIgzAyQgzAzhIAAItXAAIiNC3g");
	this.shape_27.setTransform(116.9,55);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#B0BEC5").s().p("AA8EpIi4gRQgEgBgEgDQgDgEAAgEIAAoXQAAgFADgDQAEgEAEAAIC4gRIAEAAIBIATIAAI0IhKAKIgBAAIgBAAgAhfg6QgFAAgDADQgDADAAAFIAAAMQAAAFADADQADADAFAAIB+ACQAFAAADgEQAEgDAAgFIAAgMQAAgFgEgEQgDgEgFAAgAAfh3Ih+ADQgFABgDADQgDADAAAFIAAAMQAAAEADAEQADADAFAAIB+gCQAFAAADgDQAEgEAAgFIAAgMQAAgFgEgEQgDgDgEAAIgBAAgAAfizIh+AGQgFAAgDAEQgDADAAAFIAAALQAAAFADADQADAEAFgBIB+gEQAFAAADgEQAEgDAAgFIAAgNQAAgFgEgDQgDgDgEAAIgBAAgAhfjmQgFAAgDAEQgDADAAAFIAAALQAAAFADADQADADAFAAIB+gHQAFgBADgDQAEgEAAgFIAAgMQAAgFgEgDQgDgEgFAAg");
	this.shape_28.setTransform(89.5,165.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#B0BEC5").s().p("Ag9EpIhKgKIAAo0IBIgTIAEAAIC3ARQAFAAAEAEQADADAAAFIAAIXQAAAEgDAEQgEADgFABIi3ARIgBAAIgBAAgAgmg3QgEAEAAAFIAAAMQAAAFAEADQADAEAFAAIB+gCQAFAAADgDQAEgDAAgFIAAgMQAAgFgEgDQgDgDgFAAIh+gBQgFAAgDAEgAgmh0QgEAEAAAFIAAAMQAAAFAEAEQADADAFAAIB+ACQAFAAADgDQAEgEAAgEIAAgMQAAgFgEgDQgDgDgFgBIh+gDIgBAAQgEAAgDADgAgmiwQgEADAAAFIAAANQAAAFAEADQADAEAFAAIB+AEQAFABADgEQAEgDAAgFIAAgLQAAgFgEgDQgDgEgFAAIh+gGIgBAAQgEAAgDADgAgmjsQgEADAAAFIAAAMQAAAFAEAEQADADAFABIB+AHQAFAAADgDQAEgDAAgFIAAgLQAAgFgEgDQgDgEgFAAIh+gKQgFAAgDAEg");
	this.shape_29.setTransform(143.9,165.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#B0BEC5").s().p("AhmE+QgGAAgDgEQgFgEAAgFIAAphQAAgFAFgEQADgEAGAAIDOAAQAFAAAEAEQADAEAAAFIAAJhQAAAFgDAEQgEAEgFAAgAgfB7QgOANAAATQAAATAOAOQAOAOARAAQATAAAOgOQANgOAAgTQAAgTgNgNQgOgOgTAAQgRAAgOAOgAhQg3QgDAEAAAFIAAANQAAAGADAEQAEAEAFAAICOAAQAGAAAEgEQAEgEAAgGIAAgNQAAgFgEgEQgEgEgGAAIiOAAQgFAAgEAEgAhQh5QgDAEAAAFIAAANQAAAGADAEQAEADAFAAICOAAQAGAAAEgDQAEgEAAgGIAAgNQAAgFgEgEQgEgEgGAAIiOAAQgFAAgEAEgAhQi8QgDAEAAAGIAAANQAAAGADADQAEAEAFAAICOAAQAGAAAEgEQAEgDAAgGIAAgNQAAgGgEgEQgEgDgGAAIiOAAQgFAAgEADgAhQj+QgDAEAAAGIAAANQAAAFADAEQAEAEAFAAICOAAQAGAAAEgEQAEgEAAgFIAAgNQAAgGgEgEQgEgEgGAAIiOAAQgFAAgEAEg");
	this.shape_30.setTransform(116.7,163.2);

	this.addChild(this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0.1,0,233.6,195);


(lib.ico01_mov02 = function() {
	this.initialize();

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3AiQgJgWgBg7IAAgKIAWAAQgCAJAAAPQAAAYADARQAFAbAIAAQAEAAADgHQAGgOACgOQAGAHAIAGQgJAtgUAAQgQAAgKgYgAAkgDQgIgVgOgSIAQgIQAeAkAGAwIgUAHQAAgVgKgXg");
	this.shape.setTransform(154,62.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA+QgJgHAAgMQAAgMAJgHQAKgJANABIAQABIgBgRQAAgIABgIIATABQgCAGAAAJQAAAMABAKQALAEAOAKIAIAHIgIARQgLgLgOgIIAAADQAAAJgHAIQgKAJgRAAQgNAAgKgIgAgLArQAAAKAOgBQAQABAAgNIAAgGQgHgDgIABQgPgBAAAMgAhGAlQAHgIAIgRQAIgMAHgYIgYgBIAAgSQAJACANAAIAIgBQADgOABgNIAVACIgGAYQAPgBAJgCIAAASIgFABIgYACQgFAVgMAYIgOAcgAAQgiIAKgPQAYAJAVANIgJAQQgSgNgcgKg");
	this.shape_1.setTransform(138.3,61.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhIA9QAHgJAKgWQAJgTAGgYIgcAGIgCgTQAOAAAUgDQAEgaAAgHIAAgCIAVACIgGAfIAKgBQAOAAAHAJQAIAJAAARQAAAsgMAPQgHAHgJAAQgKAAgPgFIABgHIgCgNQAOAGAJAAQAHAAACgLQADgMAAgZQAAgIgDgEQgCgFgJAAIgJABIgKAgQgHAVgMAYIgEAIgAAqgHQgGgLgFgHIAQgJQARAYAJAcIgSAJQgEgSgJgQgAAXg3IAMgHQAJAJAGAMIgMAHQgGgNgJgIgAAqhAIAMgGQAJAKAFAKIgMAHQgFgKgJgLg");
	this.shape_2.setTransform(122.8,61.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAEA6QAQgIAMgMQgIgLgGgRIANgGQAEANAGAIQAGgJADgMIghAAIAAgOIANABIATAAIALgBIAIAJIgCAFQgGASgJAPQAIAJAOAIQgEAJgDAIQgQgKgJgLQgLAMgQAKQgDgHgHgHgAgXBGIABiMIApAAIAAA0IgaAAIAAAQIAWgBIAAAPIgWgBIAAAQIAXAAIAAAQIgXAAIABAbgAgHghIAMAAIAAgVIgMAAgAhIA8QAAgFAAgQIAAhqIArAAIAAB5IgQAAIAAgJIgLAAIAAAPgAg4AeIALAAIAAghIgLAAgAg4gSIALAAIAAghIgLAAgAAYgjIAKABIAPAAIAAgUIgPAAIgKAAIAAgRIAqABIAAAzIgeAAIgMABg");
	this.shape_3.setTransform(107.3,62.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaA7QgKgHAAgLQAAgKAIgHQAIgGAMAAQAPAAALANQAEAGADAIQATgHAAgQQAAgJgIgGQgJgGgPAAQgiAAgeAbIgLgRQAGgDARgKQAcgWASgUIADgDIgsADIgHABIgBgTIATABIAugCQAHgBADgBIAKAOIgxAqIgGAEIAAAAQARgHAPAAQAUAAAMAKQANAHAAARQAAAXgWAMQgQAJgXAAQgTAAgKgHgAgSAoQAAAKASAAIAIAAQgFgRgLAAQgKAAAAAHg");
	this.shape_4.setTransform(91.4,62.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAIBKIABgTIAAhYIgDAAQgHATgSASQgEgFgHgIQARgRAKgYQAEgPABgIIATAFIgEAJIgEAKIAsAAIARgBIAAASIgRgBIgfAAIAAAUIAqgBIAAAQIgQgBIgaAAIAAAUIAaAAIAQgBIAAASIgQgBIgaAAIAAASQAAANACAGgAgzBKIABgUIABg+IgQARQgDgJgFgIQASgRANgbQAFgMABgKIASAHIgPAiIAABXQAAALACAJg");
	this.shape_5.setTransform(76.1,61.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXA+QgMgGAAgOQAAgJAHgJQAKgNAXgKQgCgGgGAAQgOAAgTAOQgIAHgGAIIgPgPIAPgLQAOgSAFgKIABgCIgdgBIAAgSQAJACAcABQAFgMACgJIASADIgEAOIgCADIAIgBQAcgBAPgEIABATIgNAAQgWADgZABQgGANgIAIIAAABIAEgDQAJgHAMAAQARAAAFARIAZgJIALgFIAIARQgHABgLADIgYAJIAAAcIgSAAIAAgXIgMAJQgJAGAAAHQAAAMAZAAQAeAAARgHIACAVIgIABQgWADgSAAQgWAAgMgIg");
	this.shape_6.setTransform(60.7,61.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgtBKIABg6QgKAYgKAMQgEgJgFgHQAJgJAJgOIAIgRIgXABIAAgRIAaABIgBg2IASAAIgBAQIAAAmIAUgBIAAARIgSgBQAJANALAKIgEAJIAMgDIAlgIIAAhaIATAAIgBBXIAOgEIADASIgPADIgCAAIABAqIgTAAIAAgnIghAIIgOAFIgDgSIgCAFQgJgKgHgMIABAtIABARgAgGgKIAJgMQARALAMALIgMANQgOgOgMgJgAgbgdQAHgRAEgTIAOAHQgFARgIASgAhHg6IANgGQAHARAEASIgOAGQgEgVgGgOgAAAgxIAIgNQAQALAMAMIgKAOQgNgNgNgLg");
	this.shape_7.setTransform(45.5,62.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhJA8QAcgDAPgIIgXABIAAg/IAYABQgCgFgEgFIgfAMIgFgQQARgEAWgKIAEANIgFAEQAQgDAIgDQALgHADgLIgNAAIgPANQgFgHgGgEQAVgOAEgOIAPACIgGAKIA8gBIAJAIIgDAGQgGAIgIAIQgJgEgGgCIALgJIgZAAQAHAYAsACQgEAHgDAIIgOgDIAAA7IgYgBQAPAIAdACQgFAFgFAKQgSgDgKgDQgLgEgNgIIAJgHIgqAAIAKAHQgVANgeAGQgEgKgGgFgAgkAkIBIAAIAAgFIhIAAgAgkAUIBIAAIAAgGIhIAAgAgkAEIBIAAIAAgFIhIAAgAAAgTQgFAFgLACIA6AAQgTgIgIgOQgGAKgJAFgAhDg6IAJgNQAQAIALAHIgLANQgMgIgNgHg");
	this.shape_8.setTransform(29.4,62);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag3AjQgJgYgBg6IAAgKIAWAAQgCAJAAAPQAAAYADARQAFAbAIAAQAEAAADgHQAGgOACgOQAGAHAIAGQgJAtgUAAQgQAAgKgXgAAkgDQgIgVgOgSIAQgIQAeAlAGAvIgUAIQAAgWgKgXg");
	this.shape_9.setTransform(224,29.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUA/QgJgIAAgMQAAgMAJgIQAKgHAOgBIAPACIgCgRQAAgIACgHIATABQgCAFgBAJQAAANACAIQAMAFANAKIAIAGIgJASQgJgLgPgJIAAAEQAAAJgGAIQgLAJgQAAQgOAAgKgHgAgLAqQAAAKAOAAQAQAAAAgNIAAgFQgHgCgHgBQgPABgBAKgAhGAlQAJgJAGgQQAHgMAJgYIgZAAIAAgSQAIABAOAAIAHAAQAFgPAAgNIAVACIgGAZQAPgCAIgDIABASIgFABIgYAEQgFAUgMAYIgOAcgAAQghIAJgQQAYAJAWAMIgJARQgSgNgcgJg");
	this.shape_10.setTransform(208.3,28.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AguBFIABgZIAAgWIAAAAIgMAOIgHAJIgJgTIAcgaIABgXQgSABgHABIgBgTIAHABIATgBIABgGIgBgWIAVAAIgCAbIACgBIAGAHIgHAHIgCADIAAAKIgBACIABAAQAFgGAOgLQASgOAOAAQAKAAAGAFQAGAHAAAJQAAAIgEAPQgGAcAAAIQAAAHAGABQAFAAAGgJQAGgIAEgKQADAIAHALIgLAQQgKAMgOAAQgIAAgFgFQgJgGAAgOQAAgMAHgbQADgOAAgFQAAgGgGAAQgIAAgMAJQgSAPgJAJIAAA9g");
	this.shape_11.setTransform(192.9,29);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgpA+QABgLgDgJQAXAHAUABQAPAAALgHQAKgGABgLQgBgIgHgEQgHgFgMAAQgVAAgSAMQgDACgEAFIgUgBIAJg/IAUABQgDAMgEAZIgBAFIABAAQAGgHAOgCQAOgEAMAAQAUAAANAHQAMAKAAAPQAAATgRAMQgOALgaAAQgSAAgXgGgAgigzIAJgQQAJAFAQAGQATAFAOACIgHASQgjgHgZgNg");
	this.shape_12.setTransform(178,28.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAmA8QgYgDgNgHQgVgNAAgaQAAgTAPgRQAIgKAMgGIg0AFQgMABgOACIgBgUICAgHIABAUIgDAAQgOAAgSAIQgeASAAAXQAAAUATAGQANAEALAAIADAAIgCAWIgGgBg");
	this.shape_13.setTransform(163.4,29.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgmA7QgQgKAAgeIABhVIAXABQgCAGgBAQIgBA4QAAAUAEAGQAGAIAPABQAagBALgbQAGgMABgNQAMAHAIADQgJAfgKALQgSATgcAAQgSABgKgIg");
	this.shape_14.setTransform(150.5,29);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAPBHQgBgLgEgGIAUACIAIgBQAAAAABAAQAAgBAAAAQAAgBAAAAQABgBAAAAIAAhLIgVAAIgPABIAAgRIAkAAIAAgMQAAgPgBgEIATAAIgBATIAAAMIACAAIAPgBIAAASIgEAAIgLgBIgCAAIAABMQAAAKgDAEQgFAFgPAAIgTgBgAhJA5QAVgRAMgWQgLgNgQgPIALgMIAXAXQAFgRABgPIgtAAIAAgRIAfABIAAgJIgBgPIASAAIAAAYIAYgBIAAARIgKAAQgCAYgIAWIAUAfIgKAOIgTgcQgMAVgUATQgEgHgIgIgAgCgFIAMgIQAOAQAJATIgPAKQgJgYgLgNg");
	this.shape_15.setTransform(134.8,28.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgCBGQgGgCAAgIIAAg7IgBgOIARAAIgBBAQAAABAAABQABAAAAABQAAAAAAABQABAAAAAAQACABAHAAQAKAAABgEQACgEAAgVQAJAEAIABQgCAdgEAFQgFAHgTAAQgRAAgDgDgAhKA7QAIgOACgOQAEgUAAgtIgBgXIARABIAoAAIAAgQIARAAIgBAQIAqAAIASgBIAAASIhHgBQAXANARAOIgNANQgPgPgXgOIAKgLIgrAAQgBA0gDAUQgDAXgKASQgGgHgIgHgAgtA0QAGgMADgOIAEgdIAQADQgDAjgJAcgAAnACIAQgFQANAbAHAbIgRAJQgGgggNgag");
	this.shape_16.setTransform(118.7,28.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhBBKIAAg1IAnAAIAKAAIAAAmIABANIgQAAIAAgGIgSAAIAAAIgAgxA0IASAAIAAgRIgSAAgAAwBJIAAgHIgnAAIAAAHIgQAAIAAhBIAaABIAAgTIgNAAIgRABIAAgSIARABIANAAIAAgUIgaADQgBgGgEgJQATgBAVgEQAWgEAKgGIAJAQIghAIIAAAXIASAAIASgBIAAASIgSgBIgSAAIAAATIAegBIABBBgAAJAzIAnAAIAAgbIgnAAgAgbANIgmAAIAAgNIAnAAIAKAAIAAANIgLAAgAgagHIgnAAIAAgPIAnAAIAKAAIAAAPIgKAAgAgZgeIguABIAAgQIA7AAIAAAQIgNgBgAhBg0IAAgPIAxAAIAAAPg");
	this.shape_17.setTransform(102.8,28.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgEBFQgGgCAAgIIAAgLIgfAAIAAAIIgRAAIAAg6IBxAAIAAAmQAIAEAJACQgBATgGAFQgFAFgkAAQgXAAgFgCgAAFA2IABACQAEACASAAQATAAAEgCQADgCAAgGIgxAAgAAFAjIAhAAIAAgIIghAAgAgpAjIAfAAIAAgIIgfAAgAAFAQIAhAAIAAgHIghAAgAgpAQIAfAAIAAgHIgfAAgAgLgGIABgfIgsAAIAAAXIgRAAIABgNIAAgXIA8ABIAAgGIgzAAIAAgPIATABIBSAAIASgBIAAAPIg1AAIAAAGIA/gBIAAAkIgRAAIAAgXIguAAIAAAQIABAPgAAlgHIgQAAIgJAAIAAgKIAJAAIAYAAIAAAKIgIAAgAgZgHIgOAAIgIAAIAAgKIAIAAIAWAAIAAAKIgIAAgAAlgWIgQAAIgJAAIAAgKIAJAAIAYAAIAAAKIgIAAgAgZgWIgOAAIgIAAIAAgKIAIAAIAWAAIAAAKIgIAAg");
	this.shape_18.setTransform(86.9,29);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAmA8QgXgDgPgHQgUgNAAgaQAAgTAPgRQAHgJANgHIg0AFQgLABgPACIgCgUICCgHIABAUIgEAAQgOAAgRAIQgfASAAAXQAAAUAUAGQAMAEALAAIAEAAIgEAWIgFgBg");
	this.shape_19.setTransform(71.4,29.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAIAyQgLgMgcgWQgOgKAAgIQABgHAFgGIAOgMQAXgRAMgNQAIgJAEgFIASAPIgUARQgOANgWARQgGAFAAADQAAABAOAJQAYAUAZAXIAEADIgQARQgGgIgPgOg");
	this.shape_20.setTransform(57.7,29);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgmA7QgQgKAAgeIABhVIAWABQgBAGAAAQIgCA4QAAAUAEAGQAFAIAQABQAZgBAMgbQAFgOADgLQAKAHAJADQgIAdgLANQgSATgcAAQgSABgKgIg");
	this.shape_21.setTransform(45.1,29);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgyBJIABgUIAAhsIgBgRIATAAIgBARIAAARIAJgEQAFAMAFATIgMAEQgDgRgEgLIAABYIABAUgAACBBQgIgDAAgNIAAhMIgKABIAAgTQAEABAMAAIAQAAIgBgcIATAAIgBAcIAWAAQAOAAAEgBIAAATIgSgBIgtAAIAABHQAAAFAEABQADABAQAAQATAAARgCIABASQgSABgWAAQgVAAgHgDgAhIAAQAGgTAAgWIAOACQgBAZgGATg");
	this.shape_22.setTransform(29.2,29);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAFAFAAAGQAAAHgFAFQgGAGgHgBQgGABgFgGg");
	this.shape_23.setTransform(13.6,67.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgEQgEgFAAgGIgMhOQgBgJAHgHQAIgIAMAAQANAAAIAIQAHAIgBAIIgMBOQAAAGgEAFQgFAEgGAAg");
	this.shape_24.setTransform(13.6,58.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAFAFAAAGQAAAHgFAFQgGAGgHAAQgGAAgFgGg");
	this.shape_25.setTransform(13.6,36.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAAA7QgFAAgFgFQgEgEAAgHIgMhNQgBgJAHgHQAIgIAMAAQANAAAIAIQAHAIgBAIIgMBNQAAAHgEAEQgFAFgGAAg");
	this.shape_26.setTransform(13.6,28.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F44336").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGAAQAHAAAGAFQAEAFAAAGQAAAHgEAFQgGAGgHgBQgGABgFgGg");
	this.shape_27.setTransform(13.5,67.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F44336").s().p("AgKA3QgFgFABgGIgNhOQgBgJAIgHQAIgIAMAAQANAAAIAIQAIAIgBAIIgNBOQAAAGgEAFQgFAEgGAAQgFAAgFgEg");
	this.shape_28.setTransform(13.5,58.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F44336").s().p("AgLAMQgGgFAAgHQAAgGAGgFQAFgFAGgBQAHABAGAFQAEAFAAAGQAAAHgEAFQgGAGgHAAQgGAAgFgGg");
	this.shape_29.setTransform(13.5,36.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F44336").s().p("AgKA2QgFgEABgHIgNhNQgBgJAIgHQAIgIAMAAQANAAAIAIQAIAHgBAJIgNBNQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_30.setTransform(13.5,28.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F44336").s().p("AiMFuItVAAQhIAAgzgzQgzgyAAhIIAAo5QAAhHAzgzQAzgyBIAAIfDAAQBIAAAzAyQAzAzAABHIAAI5QAABIgzAyQgzAzhIAAItXAAIiOC3g");
	this.shape_31.setTransform(116.8,55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#B0BEC5").s().p("AhZCpQgqglgSg6QgFgEgJgUIgDgHQgHgNADgOQABgOAKgFIAAgBQgBhgAZgqQAkg+BjgBQBjAAAkA/QAZAsAABdIAAACQAKAEACAOQABAOgGANIgDAHQgHASgHAGQgRA6gpAlQgrAlgwAAIgBABQgvgBgqgkgAiVAUQAAAHADAGIAEAJIAIAQQADACABAFQARA0AkAhQAlAiApAAQAqgBAlghQAkgiAOg1QABgEAFgCIAIgQIADgJQAEgHgBgGQAAgGgEgCIAAAAQgEgBgDgFIgeAIIgBAAQgEAAgCgCIgKgXQgSAEgYAAQg7AAhSgUIgQAkQgCAEgEgBIgagEQgCADgEACIAAAAQgEACAAAGg");
	this.shape_32.setTransform(116.3,142.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#B0BEC5").s().p("AjrATIAAglIHXAAIAAAlg");
	this.shape_33.setTransform(116.4,203.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#B0BEC5").s().p("AibBaIAAizIE3AAIAACzg");
	this.shape_34.setTransform(117,190.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#B0BEC5").s().p("AAmDKIAAjKIgWgUIioAAIBli0IBIANQAPADALALQALAKAEAOIBZEdQAGAZgPAVQgQATgaABg");
	this.shape_35.setTransform(133.1,179.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#B0BEC5").s().p("AhjDKQgaAAgQgUQgPgVAGgYIBZkeQADgNAMgLQALgKAOgDIBJgPIBlC1IidAAIgVAUIAADKg");
	this.shape_36.setTransform(99.7,179.4);

	this.addChild(this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,233.7,205.5);


(lib.ico04_mov = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		/* ムービークリップを停止
		ステージ上の指定したムービークリップを停止します。
		
		手順 :
		1. 現在再生中のムービークリップで、このコードを使用します。
		*/
		
		this.movieClip_1.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(2));

	// レイヤー 3
	this.instance = new lib.ico04_mov02();
	this.instance.setTransform(116.8,102.7,0.96,0.96,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:97.1,scaleX:1.02,scaleY:1.02,y:97},0).wait(1).to({scaleX:1.04,scaleY:1.04,y:96.9},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:96.8},0).wait(1).to({regY:102.7,scaleX:1.05,scaleY:1.05,y:102.7},0).to({scaleX:1,scaleY:1},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,4.1,224.2,186.5);


(lib.ico04_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0BEC5").s().p("Ag4AVIAAgqIBxAAIAAAqg");
	this.shape.setTransform(114.3,150.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B0BEC5").s().p("AhoBFIChhFIAAAAIihhEIAAgvIDRBgIAAAnIjRBgg");
	this.shape_1.setTransform(88.1,150.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B0BEC5").s().p("AmIGJQgbAAgTgUQgTgSAAgcIAAqOQAAgaATgUQATgTAbAAIMRAAQAbAAAUATQASAUABAaIAAKOQgBAcgSASQgUAUgbAAgAmIFHIMRAAIAAorIsRAAgAkLlNQgKAKAAANQAAAOAKAJQAJAKAOAAQANAAAKgKQAJgJAAgOQAAgOgJgJQgKgKgNAAQgOAAgJAKgAlulNQgJAKAAANQAAAOAJAJQAKAKAOAAQANAAAJgKQAKgJAAgOQAAgOgKgJQgJgKgNAAQgOAAgKAKg");
	this.shape_2.setTransform(107.8,157.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("Ag6A1QAQgdAJgsIgCAAIgIAAIgEAAIgIAAIAAgQIATABIAGAAQACgLABgLIAAgCIASACIgEAVQANgCAJgCIAAAQIgEABIgVADQgDAPgGATQgDAPgMAfgAAAA0QgKgGAAgLQAAgLAKgOIANAGQgIAJAAAGQAAALAVAAQAPAAARgFIABARIgHABIgaADQgSAAgIgGgAAAgNQAXgEARAAIANAAIABARIgSgBQgTAAgRACg");
	this.shape_3.setTransform(156.7,57.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgWAXIACAAQALAAAJgCQANgDAIgHQAKgHAAgKQAAgQgXAAQgNAAgVAFIgRAFIgEgRIAPgDQAdgGANAAQAWAAAKAPQAGAIAAAKQAAAMgKALQgJALgRAFQgJACgTADQgCgIgEgIg");
	this.shape_4.setTransform(143.2,60);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgRA3QgJgGABgMQgBgKAJgHQAJgGALgBIANACIgBgPQAAgGACgIIAPABQgBAGAAAHIABATQANAGAKAGIAHAGIgIAQQgJgKgNgHIAAACQAAAJgFAHQgIAHgQAAQgMAAgIgGgAgJAlQAAAJALAAQAPAAAAgLIAAgGQgHgCgGABQgNAAAAAJgAg9AhQAIgLAFgMQAIgNAGgSIgWAAIAAgQQAHABAMABIAHgBQAEgPAAgJIASABIgFAXQANgCAIgDIAAAQIgFABIgUADQgGAUgJATIgNAYgAAOgdIAIgNQAaAJAOAJIgHAPQgTgMgWgIg");
	this.shape_5.setTransform(131.1,57.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AAHAsQgLgNgXgRQgMgJAAgHQAAgGAFgFIAMgKQATgOAMgNQAHgIADgEIAQANIgRAPQgKAJgWASQgFAEAAABQAAABAAAAQAAABABAAQAAAAAAAAQAAAAABAAIALAJQAVARAVATIAEAEIgOAOQgHgJgMgKg");
	this.shape_6.setTransform(117.6,58.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgRA3QgIgGAAgMQAAgKAIgHQAJgGALgBIANACIgBgPIABgOIARABQgCAHAAAGIABATQAMAGAKAGIAFAFIACABIgHAQQgHgIgPgJIAAACQAAALgGAFQgHAHgQAAQgMAAgIgGgAgJAlQAAAJAMAAQAOAAAAgLIgBgGQgGgCgGABQgNAAAAAJgAg9AhQAIgMAGgLQAGgKAHgVIgWAAIAAgQQAHABAMABIAHgBQADgOABgKIASABIgFAXQAMgCAIgDIABAQIgFABIgUADQgGATgJAUIgNAYgAAOgdIAIgNQAaAJAOAJIgIAPQgRgMgXgIg");
	this.shape_7.setTransform(106.4,57.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("Ag/AzQAIgLAHgPQAHgRAGgVIgZAEIgBgQIAegDQADgVAAgHIAAgDIASACIgFAcIAJgBQAMAAAGAIQAHAHAAAQQAAAlgLAOQgFAGgIAAQgJAAgNgEIAAgGIgBgMQAMAFAIAAQAGAAACgJQADgLAAgVQAAgIgDgDQgBgEgJAAIgIABIgIAcQgGAPgLAYIgDAHgAAkgIQgGgOgKgKIAPgHQAUAXAJAeIgQAIQgFgSgHgMg");
	this.shape_8.setTransform(93.1,57.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("Ag+AyQAKgPADgTQADgTAAgrIgBgQIBuAAIAAApIgoAAIAAAMIAlgBIAAA4IABAQIgQAAIAAgGIg3AAIAAAGIgPAAIAAhIIAiABIAAgMIgoAAQgBAfgEATQgEAUgJAOQgFgIgIgFgAAXArIAWAAIAAgPIgWAAgAgKArIATAAIAAgPIgTAAgAAXAQIAWAAIAAgOIgWAAgAgKAQIATAAIAAgOIgTAAgAgfgjIBPAAIAAgNIhPAAg");
	this.shape_9.setTransform(78.9,58.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("Ag/A1QAJgMAGgPQAHgQAGgVIgZAEIgBgQQAOAAAQgDQADgVAAgHIAAgCIASABIgBAEIgEAYIAJgBQAMABAGAHQAHAIAAAPQAAAmgLANQgFAGgIAAQgJAAgNgEIAAgGIgBgMQAMAFAIAAQAGAAACgJQADgMAAgUQAAgIgDgDQgBgEgJABIgIAAIgIAcQgGARgLAWIgDAHgAAlgGQgGgLgEgFIAOgHQAPATAIAaIgQAIQgEgQgHgOgAAUgwIALgGQAIAJAFAJIgLAGQgFgJgIgJgAAkg3IALgGQAHAHAGAKIgLAHQgHgMgGgGg");
	this.shape_10.setTransform(65.3,57.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgBAwIABgPIAAhaIASAAIgBAOIgBBNQAPgHAHgIQAKgMADgMQAEAFAKAGQgIATgPANQgKAKgTAHIgHADgAhAAsQAKgHAFgJQAIgMADgQQACgOAAgdIAAgNIATABIgCAgQgBAjgKAUQgFAMgOAOQgHgKgIgEg");
	this.shape_11.setTransform(51.6,58.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("Ag7AJIAAgRIAXABIBJAAIAXgBIAAARg");
	this.shape_12.setTransform(38.5,58);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("Ag1AsQAUgLAQgOQAJgHAIgMQgPgLgVgMIAMgMIAhAXQARgdACgQIATAGIgEAKQgMAcgIAMQANAJASATIgNAOQgKgMgTgSQgJANgLALQgNALgUAMQgEgHgIgHg");
	this.shape_13.setTransform(24.5,58);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgwAeQgHgUgBgzIgBgJIAUAAQgCAFAAARQAAAXADAMQAEAYAHAAQAEAAACgGQAGgLABgOQAHAGAGAGQgJAngRAAQgOAAgJgVgAAggCQgIgUgMgOIAPgHQAZAeAGArIgRAGQgBgVgIgRg");
	this.shape_14.setTransform(127.2,29.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("Ag6A1QAQgcAJgtIgCAAIgIAAIgMAAIAAgQIATABIAGAAQADgNAAgJIAAgCIASACIgEAVQANgCAJgCIAAAQIgEABIgVADIgJAiQgDAPgMAfgAAAA0QgKgGAAgLQAAgKAKgPIANAGQgIAKAAAFQAAALAVAAQAQAAAQgFIABARIgHABIgaADQgSAAgIgGgAAAgNQAXgEARAAIANAAIABARIgSgBQgSAAgSACg");
	this.shape_15.setTransform(113.6,28.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AghA0QgOgJAAgbIAAhJIAUAAIgDBEQAAARAEAGQAFAHAOAAQAVAAAKgYQAFgLACgKQAIAEAJAFQgJAagIAJQgPASgZAAQgOAAgKgGg");
	this.shape_16.setTransform(100.9,29);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AhAAuQAPgJANgNQARgRAHgWQAEgQABgNIggABIAAgRIAkABIALgBIAAAJQAAAdAOAYQAJAPAOAMQAJAJALAGQgGAHgFAJQgVgPgOgSQgHgJgFgLQgFgKgCgIQgFAXgNARQgNARgWAPQgEgJgHgGg");
	this.shape_17.setTransform(88.1,29.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AAFBBQgCgKgDgEIARAAQAFAAAAgCIAAgIIgrAAQAIAFAIAIIgLAKQgIgJgLgJIAIgFIgRAAIgRABIAAgPIBTABIAAgEIgQAAQgTAAgKgCQgIgEgFgHQgHAFgPAJIgFgPQAJgDALgHIAAgPIgJAAIgJABIAAgOIAVABIALgBIgBAcQAEAHAIADQAFACATAAQApAAARgCQgCAGgBAHIgYABIAAAEIAYgBIAAAPIgRgBIgHAAIAAAMQAAAIgEACQgFACgMAAgAgTAHIAAgsIAXAAIACgDIghAAIAAgNIAUABIgGgKIANgCQAFAHACAFIAOAAIAHgMIAQADIgHAJIAXgBIAAANIgnAAIgCADIAgAAIAAAsgAgFAAIApAAIAAgEIgpAAgAgFgMIApAAIAAgEIgpAAgAgFgXIApAAIAAgEIgpAAgAg8g1IAJgJQAOAKAJAIIgLALQgJgKgMgKg");
	this.shape_18.setTransform(74.1,29);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgUA3QgKgGAAgMQAAgJAGgHQAJgLATgJQgBgFgGAAQgMAAgQAMIgNANIgMgNQAFgDAHgHQALgNAGgLIABgCIgaAAIAAgQQAIACAZAAQAFgKAAgIIARACIgEANIgBADIAHgBQAZgCALgDIABAQIgLABQgNACgbABQgFALgIAIIAAAAIADgCQAIgGALAAQAPAAAEAOIAVgHIALgEIAGAOQgFAAgKAEIgVAHIAAAZIgQAAIABgUIgMAIQgHAFAAAGQAAAKAWAAQAbAAAOgGIABATIgGAAQgRADgTAAQgTAAgKgGg");
	this.shape_19.setTransform(59.9,28.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgbAyQgIgFgEgLQgCgDgBgIIAUgCQABAIADAEQAGAIANAAQAWAAAAgRQAAgJgHgDQgEgCgSgFQgQgEgGgDQgKgIAAgPQAAgOALgJQAKgJARAAQAYAAAKAPQAEAFADALIgUACQgBgHgDgDQgGgHgLAAQgIAAgFAFQgGAEAAAHQAAAIAJAEIASAGQAPACAIAFQAMAHAAAQQAAAQgJAIQgLALgXAAQgQAAgLgIg");
	this.shape_20.setTransform(48.9,28.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AAnA3IABgUIABhCIgGAUIgVAwQgEAJgCAJIgPAAIgGgTIgUguIgHgVIABBCQAAAMABAIIgUAAQACgIAAgMIAAhEQAAgMgCgJIAaAAQACAJADAIIAbBDIAchDIAFgRIAaAAIgBAVIAABEQAAAPABAFg");
	this.shape_21.setTransform(37,28.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AggAsQgQgRAAgbQAAgbARgRQANgNAUABQAPAAAMAGQAJAHAFAIQADAEACAHIgUAFQgCgJgEgDQgHgJgNAAQgOAAgIALQgIALgBASQABASAIAMQAJALANAAQAPAAAHgKQAEgHABgHIAUAEQgEAOgFAHQgNAQgZAAQgVAAgNgOg");
	this.shape_22.setTransform(24.6,29);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_23.setTransform(12.3,62.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F44336").s().p("AAAA3QgFAAgEgFQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAFgFAAg");
	this.shape_24.setTransform(12.3,54.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_25.setTransform(12.3,34.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F44336").s().p("AAAA3QgFgBgEgEQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAEgFABg");
	this.shape_26.setTransform(12.3,26.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#B0BEC5").ss(1,1,1).p("AuSn9QhCAAgvAvQgvAvAABCIAAIRQAABCAvAvQAvAvBCAAIMRAAIB+CqICCiqIMUAAQBCAAAvgvQAvgvAAhCIAAoRQAAhCgvgvQgvgvhCAAg");
	this.shape_27.setTransform(107.5,51);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AiBFUIsRAAQhCgBguguQgwgvABhDIAAoQQgBhCAwguQAugwBCABIclAAQBCgBAuAwQAwAugBBCIAAIQQABBDgwAvQguAuhCABIsUAAIiBCqg");
	this.shape_28.setTransform(107.5,51);

	this.instance = new lib.ico04_mov();
	this.instance.setTransform(108,97.5,1,1,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance}]},1).wait(1));

	// レイヤー 2
	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("Aq/IWIAAwsIWAAAIAAQsg");
	this.shape_29.setTransform(105.5,156.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_29).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,217,211);


(lib.ico03_mov = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		/* ムービークリップを停止
		ステージ上の指定したムービークリップを停止します。
		
		手順 :
		1. 現在再生中のムービークリップで、このコードを使用します。
		*/
		
		this.movieClip_1.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(2));

	// レイヤー 3
	this.instance = new lib.ico03_mov02();
	this.instance.setTransform(116.8,102.7,0.96,0.96,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:99.3,scaleX:1.02,scaleY:1.02,y:99.3},0).wait(1).to({scaleX:1.04,scaleY:1.04,y:99.2},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:99.1},0).wait(1).to({regY:102.7,scaleX:1.05,scaleY:1.05,y:102.7},0).to({scaleX:1,scaleY:1},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,4.1,224.2,190.7);


(lib.ico03_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0BEC5").s().p("AiuFzQhghJgphyIg5AAQgiAAgXgWQgYgYABghIAAhXQAAgUALgUQALgSAUgKQABi8BrhkQBqhlDAABQDBgBBqBlQBsBkAAC8QAUAKALASQALAUAAAUIAABXQABAhgYAYQgXAWgiAAIg5AAQgpByhhBJQhYBFhWAAQhVAAhZhFgAhsFcQA8AkAwgBQBXABBZhYQBphngBiVQABgcgDgdQgbgYgugSQgwgRg8gGQATAUAHAcQgPgLhXgdQhLgbgrgyIgLgOIgOgUQgDgEAAAHQgCBKguA2QgtA0g8AIIgBAiQgBA8AUA3QA2BCCAAHQAKgOASgJQAUgKAXABQAeAAAXAQQAWAQABAXQgBAWgWAQQgXARgegBQgYABgUgKQgUgKgIgQQhVgFg3gaQAsBBBDAogAECjvQA2BFARBvIAeAAQgDijhchVQhbhUitAAQisAAhbBUQhcBVgECjIAfAAQARhvA2hFQBXhvCqAAQCrAABXBvgABTBMQgNgNAAgTQAAgUANgNQAPgMATAAQASAAAOAMQANANAAAUQAAATgNANQgOAOgSAAQgTAAgPgOgAiUBMQgNgNAAgTQAAgUANgNQAOgMATAAQASAAAPAMQANANAAAUQAAATgNANQgPAOgSAAQgTAAgOgOg");
	this.shape.setTransform(108,158.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgvAeQgJgTAAg0IgBgJIATAAIgBAWQAAAXADAMQADAYAIAAQAEAAACgGQAFgLACgOQAFAFAHAHQgIAngRAAQgOAAgIgVgAAggCQgHgSgNgQIAOgHQAaAfAGAqIgRAGQgCgVgHgRg");
	this.shape_1.setTransform(173.9,57.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgRA3QgJgHABgKQgBgLAJgHQAJgGALgBIANACIgBgPQAAgGABgIIAQABQgBAGAAAHIABATQANAGAKAGIAGAHIgHAPQgIgJgOgIIAAACQAAAJgFAHQgIAHgQAAQgMAAgIgGgAgJAlQAAAJAMAAQANAAAAgLIAAgGQgGgBgGAAQgNAAAAAJgAg9AgQAIgKAFgMQAIgNAGgSIgWAAIAAgQQAHACAMAAIAHgBQAEgPAAgJIASABIgFAXQANgCAHgDIAAARIgEAAIgUADQgGAUgJATIgNAXgAAOgdIAIgNQAaAJAOAJIgHAPQgTgMgWgIg");
	this.shape_2.setTransform(160.2,56.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgjA2QAAgJgCgJQAVAHAQAAQANAAAKgFQAJgGAAgJQAAgHgHgEQgGgEgLAAQgRAAgQAKIgGAGIgSAAIAIg4IASABQgEAOgDATIAAAEIAAAAQAOgLAaAAQASAAALAGQALAIAAAOQAAAQgPALQgNAJgWAAQgPAAgUgFgAgegsIAIgOQAIAEAOAFQARAFAMABIgGARQgdgIgYgKg");
	this.shape_3.setTransform(146.9,56.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("Ag/AzQAHgJAIgRQAHgRAHgVIgaAEIgBgQIAegDQADgVAAgHIAAgDIASACIgFAcIAJgBQALAAAIAIQAGAIAAAPQAAAmgLANQgFAGgIAAQgJAAgNgEIABgGIgCgMQAMAFAJAAQAFAAACgJQADgLAAgVQAAgIgDgDQgBgEgJAAIgIABIgIAcQgGAPgLAYIgDAHgAAlgIQgIgPgJgJIAPgHQAUAXAJAeIgQAIQgDgPgIgPg");
	this.shape_4.setTransform(134.5,56.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgkA8QABgEAAgSIAAgVIgHAHQgFAFgFAHIgIgQIAZgVIABgUIgVACIgBgQIAEAAIASgBIAAgXIASAAIgCAUIAAACIACAAIAGAFIgIAJIgBAKIABAAIADgDQATgPATAAQAQAAAMALQAKALAAAQQAAAdgWALQgLAFgOAAQgLAAgIgDQAAgLgDgHQAKAFAOAAQAMAAAIgIQAIgIAAgNQAAgJgHgHQgFgGgMAAQgSAAgUATIgBAOQAAAhABAJg");
	this.shape_5.setTransform(120.7,57);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("Ag/A1QAHgIAIgTQAIgQAGgVIgZAEIgCgQQAPAAAPgDQADgVAAgHIAAgCIATACIgCADIgEAYIAJAAQAMAAAHAHQAGAIAAAPQAAAngLAMQgEAGgJAAQgJAAgNgEIABgGIgCgMQAMAFAJAAQAFAAACgJQADgNAAgTQAAgHgDgEQgBgDgJAAIgIAAQgDANgFAPQgIAVgJASIgDAHgAAlgGQgFgIgFgIIAOgHQAPATAIAaIgQAIQgEgRgHgNgAAUgwIALgGQAIAJAFAJIgLAGQgFgKgIgIgAAkg3IALgGQAIAIAFAJIgLAHQgFgKgIgIg");
	this.shape_6.setTransform(107.1,56.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgaBAQgBgHgDgHIARACQAGAAgBgEIAAgGIguAAIAAgNIAuAAIAAgFIgnAAIgQABIAAgOIA3ABIAAgGIguAAIAAgKIAuAAIAAgFIgpABIAAgdIApABIAAgGIg2ABIAAgNIA2AAIAAgJIAPAAIgBAJIA4AAIAAANIg4gBIAAAGIAsgBIAAAdIgsgBIAAAFIAuAAIAAAQIAMgBIAAAOIgMgBIAAAXIgPAAIAAgFIgfAAIAAAHQAAAKgEADQgCACgNAAgAAGAdIAfAAIAAgFIgfAAgAAGAMIAfAAIAAgGIgfAAgAAGgTIAcAAIAAgGIgcAAgAgigTIAaAAIAAgGIgaAAg");
	this.shape_7.setTransform(93.4,57);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgEAmQASgCAIgFQAUgKAAgXQAAgWgRgKQgHgEgIAAQgDAhgJAWQgMAagRAAQgMABgHgLQgIgLAAgRQAAgWAPgRQASgUAdAAQAZABAPAOQAPAOAAAYQAAAPgJAOQgJAOgQAHQgJADgNACQgCgHgFgJgAgXgfQgTAOAAAWQAAAJAEAFQADAHAEgBQAHAAAIgSQAJgRACgbQgJAAgJAGg");
	this.shape_8.setTransform(79.4,57.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("Ag7AJIAAgRIAXABIBJAAIAWgBIAAARg");
	this.shape_9.setTransform(65.9,57);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AAYANQgKgUgDgcIgCgKIARgEQABAKAFAXQAKAjAVAXQgIAFgHAIQgPgSgJgYgAhBArQAMgNAHgSQAKgQAEgdIABgOIAAgCIAUAEIgCALQgFAcgHARQgJAZgPATQgHgHgJgFgAAfgrIAKgFQAFAIAFANIgKAEQgEgKgGgKgAAugxIAKgEQAGAJAFAJIgKAFQgGgMgFgHg");
	this.shape_10.setTransform(52.5,56.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("Ag7AJIAAgRIAXABIBJAAIAXgBIAAARg");
	this.shape_11.setTransform(39.2,57);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgXAsQASgFAHgHQANgMACgUIABgRIgjAAIABAfIgSAAIAAgfIgIAAIgSACIAAgSIASABIAIAAIAAgaIASAAIgBAaIAjAAIgBgaIASAAIgBAaIAJAAIASgBIAAASIgSgCIgJAAQAAARgBAEQgDAagRAPQgKAJgQAFQgCgGgIgJg");
	this.shape_12.setTransform(25.2,57.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AgvAeQgJgTAAg0IgBgJIAUAAQgCAIAAAOQAAAUADAPQADAYAIAAQADAAADgGQAGgLACgOQAFAFAGAHQgIAngRAAQgOAAgIgVgAAggCQgHgSgNgQIAOgHQAaAfAGAqIgRAGQgBgTgIgTg");
	this.shape_13.setTransform(170.7,28.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("Ag6A1QAHgNAIgWQAGgUAEgSIgBAAIgJAAIgFAAIgIAAIAAgQIATABIAHAAIACgWIAAgCIATACIgEAVQANgCAJgCIABAQIgFABIgVADQgDAPgFATQgFAQgLAegAAAA0QgKgGAAgLQAAgLAKgOIAMAGQgHAJAAAGQAAALAVAAQAQAAAPgFIACARIgHABIgaADQgSAAgIgGgAAAgNQAYgEAQAAIAOAAIAAARIgSgBQgTAAgRACg");
	this.shape_14.setTransform(157.1,27.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AgbAtQATgDAKgFQAXgNAAgcQAAgggTAAQgGAAgHAIQgRATAAAYIAAADIgRAAIAAgUQAAgQABgUIADgWIASABQgCAEgDAXIgCAOIABAAIAAgDQADgKAGgHQALgOAOAAQAOAAAJAMQAKAOAAAYQAAAngkAQQgJAFgQADQgEgLgEgFg");
	this.shape_15.setTransform(144,28);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AAHBBIABgQIAAhNIgDAAQgHASgOAOQgDgFgHgHQAPgPAJgVQACgKACgJIAQAEIgGARIA1gBIAAAPIgqAAIAAASIAlgBIAAAMIglAAIAAARIAlAAIAAAPIglAAIAAAQQAAANABADgAgsBAIABgRIAAg2IgNAPQgDgIgFgHQAQgOALgYQAFgNABgGIAQAFIgEAIIgJAXIABBcg");
	this.shape_16.setTransform(131.6,28);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgUA3QgLgGAAgMQABgJAGgHQAIgLAUgJQgBgFgGAAQgLAAgSAMQgGAGgFAHIgOgNQAGgDAIgHQANgSADgGIABgCIgaAAIAAgQQAIACAZAAQAFgMAAgGIAQACIgEAQIAGgBQAagCAMgDIABAQIgMABQgOACgaABQgGALgHAIIAAAAIADgCQAIgGALAAQAPAAAEAOIAVgHIALgEIAGAOIgPAEIgVAHIAAAZIgQAAIABgUIgMAIQgHAFAAAGQAAAKAWAAQAaAAAPgGIACATIgHAAQgQADgUAAQgSAAgLgGg");
	this.shape_17.setTransform(117.8,27.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgoA7IAAh2IAUAAIgBAqQAcAKAiARIgLARQgQgMgfgPIgFgBIACA8g");
	this.shape_18.setTransform(105.3,28);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AAAA8IABg/QgSAKgeALQgDgJgGgHQAogIAggaQAUgSAGgJIAPAMIgEAFQgRAQgRAMIABBKg");
	this.shape_19.setTransform(93.1,28);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgXAsQASgFAHgHQANgMABgUIABgRIgiAAIAAAgIgSAAIABggIgJAAIgSABIAAgRIASABIAJAAIgBgaIASAAIAAAaIAiAAIAAgaIASAAIgBAaIAJAAIASgBIAAARIgSgBIgJAAIgBAWQgDAZgRAPQgJAIgQAHQgDgHgIgJg");
	this.shape_20.setTransform(80.4,28.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AgLAwQAMgHAIgJQAJgLAAgaIAAgJIgmAAIAAgQQAJACAOAAIAPgBIgCgfIARAAIABAeQAPgCAGgEIABARIgIABIgNADIAAAHQgBAUgDALQgDARgMAKIgPALQgGgJgGgEgAgyAxQgFgWAAgYQAAgOAFglIABgKIASACIgDARIgEAbIgBAlQAFgOAFgJIANAGQgRAdABAQIgRABg");
	this.shape_21.setTransform(67.6,28.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("Ag5A/IABgPIAAhbIAnABQAGgKACgKIAQABIgHATIA6gBIgBBbQAAAKgGADQgDACgMAAIgPgBQgBgIgDgHIASABIAGAAIABgEIAAhIIhSAAIAABbgAgcArIABgNIAAguIAJABIAjAAIALgBIgBALIAAAaIABAMIgoAAIAAAKgAgMASIAYAAIAAgTIgYAAg");
	this.shape_22.setTransform(54,27.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AARBBIABgTIAAgsQgKgHgGgKQgEAYgNAUQgOAVgVAOQgEgGgHgHIAQgMQAOgMAHgOQgGgHgLgHIAJgMIAPANQAFgKAEgWIgUAAQgKAYgRASQgEgHgGgFQARgQAJgbIAEgTIAQAEIgFAQIAegBIgBAKQAEAKAJAKIAAggIgBgPIASAAIgBAPIAAAuQAEACAJAEQAKAHAJADQgEAGgEAJQgLgFgNgKIAAAfIABATg");
	this.shape_23.setTransform(40.2,28);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("Ag/A1QABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAAAQAJgOAHgZIANAKQgFANgIATIgFAMgAAPA/QABgHgDgHIAOABQAEAAABgBQACgBAAgEIgtAAIgCALIgQgCQAGgSADgWIgCAAIgLABIAAgOIAOAAIACgUIgJAJQgDgGgHgGQALgJAHgMQAGgLACgJIAOADIgEALIA/gBIAAAPIgTgBIgyAAIgGAKIBCAAIgBAIIAAATIANAAIAAAOIgNgBIgBAAIgBARIAKgBIAAAPIgKAAIgCAAQgDANgDADQgEAEgKAAgAATAeIARAAIACgRIgQAAgAgJAeIAPAAIACgRIgOAAgAAXAAIAQAAIAAgOIgQAAgAgEAAIANAAIABgOIgNAAgAhBgQIAKgKQAMAHALALIgKAJQgLgJgMgIgAg6gzIAKgKQAMAIAJAKIgKALQgMgNgJgGg");
	this.shape_24.setTransform(25.9,28);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_25.setTransform(12.3,62.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F44336").s().p("AAAA3QgFAAgEgFQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAFgFAAg");
	this.shape_26.setTransform(12.3,54.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_27.setTransform(12.3,34.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F44336").s().p("AAAA3QgFgBgEgEQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAEgFABg");
	this.shape_28.setTransform(12.3,26.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#B0BEC5").ss(1,1,1).p("AuSn9QhCAAgvAvQgvAvAABCIAAIRQAABCAvAvQAvAvBCAAIMRAAIB+CqICCiqIMUAAQBCAAAvgvQAvgvAAhCIAAoRQAAhCgvgvQgvgvhCAAg");
	this.shape_29.setTransform(107.5,51);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AiBFUIsRAAQhCgBguguQgwgvABhDIAAoQQgBhCAwguQAugwBCABIclAAQBCgBAuAwQAwAugBBCIAAIQQABBDgwAvQguAuhCABIsUAAIiBCqg");
	this.shape_30.setTransform(107.5,51);

	this.instance = new lib.ico03_mov();
	this.instance.setTransform(108,97.5,1,1,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance}]},1).wait(1));

	// レイヤー 2
	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("Aq/IWIAAwsIWAAAIAAQsg");
	this.shape_31.setTransform(105.5,156.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_31).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,217,211);


(lib.ico02_mov = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		/* ムービークリップを停止
		ステージ上の指定したムービークリップを停止します。
		
		手順 :
		1. 現在再生中のムービークリップで、このコードを使用します。
		*/
		
		this.movieClip_1.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(2));

	// レイヤー 3
	this.instance = new lib.ico02_mov02();
	this.instance.setTransform(116.8,102.7,0.96,0.96,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:116.9,regY:97.5,scaleX:1.02,scaleY:1.02,x:116.9,y:97.4},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:117,y:97.3},0).wait(1).to({scaleX:1.05,scaleY:1.05,x:116.9},0).wait(1).to({regX:116.8,regY:102.7,scaleX:1.05,scaleY:1.05,x:116.8,y:102.7},0).to({scaleX:1,scaleY:1},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,4.1,224.3,187.2);


(lib.ico02_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0BEC5").s().p("ABKFzIjkgVQgHgBgEgFQgEgEAAgGIAAqdQAAgFAEgFQAEgEAHgBIDkgVIAGABIBbAWIAALCIheANIgBABIgCgBgAh3hJQgGAAgFAEQgEAEAAAGIAAAOQAAAGAEAFQAFAEAGAAICeABQAGAAAFgEQADgEAAgHIAAgPQAAgGgDgEQgFgFgGAAgAh3iRQgGAAgFAEQgEAEAAAHIAAAOQAAAGAEAEQAFAEAGAAICegCQAGAAAFgFQADgEAAgGIAAgPQAAgHgDgEQgFgEgGAAgAAnjhIieAIQgGAAgFAFQgEAEAAAGIAAAOQAAAGAEAEQAFAEAGAAICegFQAGgBAFgEQADgFAAgGIAAgPQAAgHgDgEQgFgEgFAAIgBAAgAAnksIieALQgGABgFAEQgEAFAAAFIAAAPQAAAGAEAEQAFAEAGgBICegJQAGAAAFgFQADgFAAgGIAAgPQAAgGgDgEQgFgEgFAAIgBAAg");
	this.shape.setTransform(73.3,160.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B0BEC5").s().p("AhMF0IhdgOIAArCIBagWIAGAAIDlAUQAGABAEAFQAEAEAAAGIAAKcQAAAGgEAFQgEAFgGAAIjlAWgAgwhFQgEAEAAAHIAAAOQAAAHAEAEQAEAEAGABICegCQAGAAAEgEQAFgFAAgGIAAgOQAAgFgFgFQgEgEgGAAIieAAQgGAAgEAEgAgwiRQgEAEAAAHIAAAPQAAAGAEAFQAEAEAGAAICeACQAGAAAEgEQAFgEAAgGIAAgOQAAgGgFgFQgEgEgGAAIiegEQgGAAgEAEgAgwjcQgEAEAAAGIAAAPQAAAGAEAFQAEAEAGABICeAGQAGAAAEgFQAFgDAAgHIAAgNQAAgHgFgEQgEgEgGgBIiegIIgBAAQgFAAgEAFgAgwkoQgEAEAAAGIAAAPQAAAGAEAFQAEAFAGABICeAJQAGAAAEgEQAFgEAAgGIAAgOQAAgGgFgEQgEgFgGAAIiegMIgBAAQgFAAgEAEg");
	this.shape_1.setTransform(141.3,160.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B0BEC5").s().p("AiBGOQgGAAgFgFQgFgFAAgHIAAr5QAAgHAFgEQAFgGAGAAIECAAQAIAAAEAGQAFAEAAAHIAAL5QAAAHgFAFQgEAFgIAAgAgoCZQgRASAAAXQAAAYARASQARAQAXAAQAYAAAQgQQASgSgBgYQABgXgSgSQgQgQgYAAQgXAAgRAQgAhkhFQgEAEgBAIIAAARQABAGAEAFQAFAFAHAAICyAAQAGAAAFgFQAFgFAAgGIAAgRQAAgHgFgFQgFgFgGAAIiyAAQgHAAgFAFgAhkiYQgEAFgBAHIAAAQQABAIAEAEQAFAFAHAAICyAAQAGAAAFgFQAFgEAAgIIAAgQQAAgGgFgGQgFgEgGAAIiyAAQgHAAgFAEgAhkjrQgEAFgBAHIAAAQQABAHAEAGQAFAEAHAAICyAAQAGAAAFgEQAFgGAAgHIAAgQQAAgHgFgFQgFgEgGAAIiyAAQgHAAgFAEgAhkk9QgEAFgBAGIAAARQABAHAEAEQAFAGAHAAICyAAQAGAAAFgGQAFgEAAgHIAAgRQAAgGgFgFQgFgFgGAAIiyAAQgHAAgFAFg");
	this.shape_2.setTransform(107.3,158.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgdA+QgCgJgDgGQAPACAJAAQAGAAgBgFIAAgWIg4AAIAAgQIA4ABIAAgPIgwABIAAgPIARABIAfAAIAAgRQgPACgdAAIgEgPIAHAAQAlABAXgFQASgEAIgDIAMAOQgWAGgVACIAAATIAdAAIARgBIAAAPIgugBIAAAPIA1gBIAAAQIg1AAIAAAbQAAAJgGADQgDACgKAAIgTgBg");
	this.shape_3.setTransform(73.8,56.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AAgBAIAAgHIg+AAIAAAHIgQAAIABg1IAlABIAAgMIg1AAIAAgPIARABIAkAAIAAgQIAPAAIgBAQIAnAAQANAAAEgBIAAAPIg4AAIAAAMIApgBIAAA1gAgeArIA+AAIAAgSIg+AAgAANgaIABgLIgcAAIAAALIgPAAIAAgLIgQAAIgQABIAAgPIAQABIAQAAIAAgNIAPAAIAAANIAcAAIgBgNIAPAAIAAANIASAAIAQgBIAAAPIgQgBIgSAAIAAALg");
	this.shape_4.setTransform(59.8,57.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("Ag/A1QAIgJAHgSQAGgNAIgYIgZAEIgCgQQAOAAAQgDQADgVAAgHIAAgCIATACIgCADIgEAYIAJAAQALAAAIAHQAGAIAAAPQAAAngLAMQgFAGgIAAQgJAAgNgEIABgGIgCgMQAMAFAJAAQAFAAACgJQADgNAAgTQAAgHgDgEQgBgDgJAAIgIAAQgDANgFAPQgIAVgJASIgDAHgAAlgGQgFgIgFgIIAOgHQAPATAIAaIgQAIQgEgRgHgNgAAUgwIALgGQAIAJAFAJIgLAGQgFgKgIgIgAAkg3IALgGQAIAIAFAJIgLAHQgFgKgIgIg");
	this.shape_5.setTransform(45.8,56.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AggAsQgQgQAAgcQAAgbAQgRQANgNAVABQAPAAALAGQAKAHAFAIQACAEACAHIgTAEQgDgIgDgDQgHgJgNAAQgNAAgJALQgJALAAASQAAASAJAMQAJALANAAQAPAAAIgKQADgHABgHIAUAEQgDANgHAIQgMAQgZAAQgWAAgMgOg");
	this.shape_6.setTransform(33.5,57);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgqA4QACgJAAgJIAAhKIgCgSIAuAAQATAAALAKQAIAJABAPQAAAPgKAJQgKAKgUAAIgZAAIAAAYIABASgAgWAAIAZAAQAUAAAAgUQAAgIgFgEQgFgGgKAAIgZAAg");
	this.shape_7.setTransform(23.3,56.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgwAeQgIgTgBg0IAAgJIATAAIgBAWQAAAXACAMQAFAYAHAAQADAAADgGQAFgNACgMQAFAFAHAHQgIAngRAAQgOAAgJgVgAAfgCQgGgSgOgQIAQgHQAZAfAGAqIgSAGQgBgVgIgRg");
	this.shape_8.setTransform(192.7,28.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgRA3QgIgHgBgKQABgLAIgGQAJgIALAAIANACIgBgPQAAgHACgGIAQABQgCAEAAAIIABATQAMAGAKAGIAIAHIgJAPQgIgKgNgHIABADQgBAJgGAGQgHAHgQAAQgMAAgIgGgAgJAlQAAAJALAAQAOAAABgMIAAgEQgHgCgGAAQgNAAAAAJgAg9AgQAIgKAGgMQAHgNAGgSIgWAAIAAgQQAIABALAAIAHAAQAEgPAAgJIASACIgFAVQANgBAIgCIAAAQIgFABIgUACQgGAUgKATIgMAXgAAOgdIAJgNQAZAJAOAKIgIANQgRgLgXgIg");
	this.shape_9.setTransform(179.1,27.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AgjA2QAAgJgCgJQAVAHAQAAQANAAAKgFQAJgGAAgJQAAgPgYAAQgRAAgQAKIgGAGIgSAAIAIg4IASABQgEAOgDATIAAAEIAAAAQAOgLAaAAQASAAALAGQALAIAAAOQAAAQgPALQgNAJgWAAQgPAAgUgFgAgegsIAJgOQAHAEAOAFQARAFAMABIgGARQgdgHgYgLg");
	this.shape_10.setTransform(165.7,27.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("Ag/AzQAHgJAIgRQAGgNAIgZQgKABgPADIgCgQIAegDQADgVAAgHIAAgDIATACIgCAFIgEAXIAJgBQALAAAIAIQAGAIAAAPQAAAmgLANQgFAGgIAAQgJAAgNgEIABgGIgCgMQAMAFAJAAQAFAAACgJQADgMAAgUQAAgIgDgDQgBgEgJAAIgIABIgIAcQgHAUgKATIgDAHgAAlgIQgHgOgKgKIAPgHQAUAXAJAeIgQAIQgDgPgIgPg");
	this.shape_11.setTransform(153.3,27.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgkA8QABgEAAgSIAAgVIgGAHQgHAFgEAHIgIgQIAZgVIABgUIgWACIgBgQIAFAAIASgBIABgRIgBgGIASAAIgBANIgBAJIACAAIAFAFIgHAJIgBAKIAAAAIAEgDQATgPATAAQAQAAALALQALALAAAQQAAANgGALQgGALgKAFQgLAFgOAAQgLAAgIgDQAAgLgDgHQAKAFANAAQANAAAIgIQAIgIAAgNQAAgJgHgHQgGgGgLAAQgSAAgVATIAAAOQAAAhABAJg");
	this.shape_12.setTransform(139.5,28);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AAHAsQgLgMgXgSQgMgKAAgFQAAgGAFgGIAMgKQASgOAMgNQAIgGADgGIAQANIgSAPIgfAbQgFAEAAACQAAAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAIAKAIQAWASAUATIAFAEIgPAOQgHgJgLgKg");
	this.shape_13.setTransform(126.5,28.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgxAxQgEgGAAgHQAAgKAKgIQAKgGAPgBIANACIAAgCIgDhHIARAAQgBAFAAARIAAAJQAcAAANgFIABARIgJABQgUACgNAAIACAeQAKADAMAGIAWAPIgLAPIgKgJQgKgHgIgEIgFgCIAAAEQAAAYgeAAQgVAAgIgMgAgjAkQAAAFAFADQAFACAFAAQAIAAAFgEQADgCAAgFIgBgHQgFgBgIgBQgRAAAAAKg");
	this.shape_14.setTransform(115.2,28);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("Ag2A1QgDgWAAgXQAAgUACgPIAGgeIAAAAIASACQgEAIgDAWQgEAWAAAQIAAAKIAAACIAAAAIAIgTIALAFQgNAcAAAPIAAAEIgRABgAgPA0QgIgHAAgKQAAgLAIgGQAIgHALAAQAIABAEACIgBgdIgcAAIgEAAIgFAAIABgQQAIACAPAAIANAAIgBgcIASAAIgBAbQAKgBAJgDIADgBIABAAIABAQIgYADIABAhQANAGAJAHIAEADIgGARQgEgGgHgDIgJgGIAAABIgBAIQgFAOgVAAQgMgBgIgFgAgHAjQAAAIAKAAQAJAAADgEQACgCAAgFIAAgEQgGgCgGgBQgMAAAAAKg");
	this.shape_15.setTransform(103.1,28);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgaBAQgBgHgEgHIASABQAGAAAAgDIAAgHIgvABIAAgNIAvABIAAgHIgpAAIgPABIAAgNIA4ABIAAgHIguABIAAgKIAuAAIAAgFIgqABIAAgdIAqAAIAAgEIg3AAIAAgOIA3ABIgBgKIAPAAIgBAKIA5gBIAAAOIg5AAIAAAEIArAAIAAAdIgrgBIAAAFIAvAAIgBAQIAMgBIAAANIgMgBIABAYIgQAAIAAgGIgfAAIAAAIQAAAKgEADQgCADgNAAgAAGAeIAfAAIAAgHIgfAAgAAGAMIAfAAIAAgHIgfAAgAAGgUIAcAAIAAgFIgcAAgAghgUIAaAAIAAgFIgaAAg");
	this.shape_16.setTransform(89.2,28);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgDAmQAQgCAJgGQAUgKAAgWQgBgVgQgLQgIgDgHgBQgEAigIAWQgMAagQAAQgNgBgHgKQgIgLAAgRQAAgWAPgRQASgUAdABQAYgBAQAOQAPAPAAAYQAAAPgJAOQgJAOgQAGQgJAFgNABQgDgJgDgHgAgXgfQgTAOAAAWQAAAJAEAFQADAHAEAAQAHgBAHgRQAKgTACgaQgJAAgJAGg");
	this.shape_17.setTransform(75.2,28.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AAmAqIgGABQgVAEg4AGIgNABIgCgTIAQAAQAJgXALgfQAJgeABgJIASAEIgDAKQgNAvgNAfQAjgDAVgFIgGgMQgHgOgHgHIAQgFQAVAcANAiIgRAJg");
	this.shape_18.setTransform(61.7,28);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgtAqQAYgHAJgQQAGgJABgPIg1AAIAAgQIASABIBQAAIASgBIAAAQIgvAAQgBAVgJAOQgIARgaALQgFgIgHgIgAgrgoIAAgRIASABIA0AAIASgBIAAARg");
	this.shape_19.setTransform(49.5,28.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AAEANQgWAageAPQgEgJgHgHQAPgGANgJQAfgXAOghIABgDIgsABIgPABIgBgSIA/AAQAIAAAFgBIAJAJIgEAIQgJAUgNAQIAaAUIAUAUIgNAOQgWgZgVgQg");
	this.shape_20.setTransform(36.3,28.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("Ag1AmQATAAAVgIQAXgLAQgTQAKgNAHgSQAFAIAJAFQgJASgMAPQgaAfgwAJIgKACgAg4gIIAJgOQAUAIASAKIgJAPQgPgLgXgIgAgtgqIAKgPQAZALAKAIIgHAPQgUgNgSgGg");
	this.shape_21.setTransform(24.1,28);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_22.setTransform(12.3,62.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F44336").s().p("AAAA3QgFAAgEgFQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAFgFAAg");
	this.shape_23.setTransform(12.3,54.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_24.setTransform(12.3,34.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F44336").s().p("AAAA3QgFgBgEgEQgEgEAAgGIgLhHQgBgJAHgHQAHgGALgBQAMAAAHAIQAHAGgBAJIgLBHQAAAGgEAEQgFAEgFABg");
	this.shape_25.setTransform(12.3,26.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#B0BEC5").ss(1,1,1).p("AuSn9QhCAAgvAvQgvAvAABCIAAIRQAABCAvAvQAvAvBCAAIMRAAIB+CqICCiqIMUAAQBCAAAvgvQAvgvAAhCIAAoRQAAhCgvgvQgvgvhCAAg");
	this.shape_26.setTransform(107.5,51);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AiBFUIsRAAQhCgBguguQgwgvABhDIAAoQQgBhCAwguQAugwBCABIclAAQBCgBAuAwQAwAugBBCIAAIQQABBDgwAvQguAuhCABIsUAAIiBCqg");
	this.shape_27.setTransform(107.5,51);

	this.instance = new lib.ico02_mov();
	this.instance.setTransform(108,97.5,1,1,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance}]},1).wait(1));

	// レイヤー 2
	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Aq/IWIAAwsIWAAAIAAQsg");
	this.shape_28.setTransform(105.5,156.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_28).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,217,211);


(lib.ico01_mov = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		/* ムービークリップを停止
		ステージ上の指定したムービークリップを停止します。
		
		手順 :
		1. 現在再生中のムービークリップで、このコードを使用します。
		*/
		
		this.movieClip_1.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(2));

	// レイヤー 3
	this.instance = new lib.ico01_mov02();
	this.instance.setTransform(116.8,102.7,0.96,0.96,0,0,0,116.8,102.7);

	this.instance_1 = new lib.ico02_mov02();
	this.instance_1.setTransform(116.8,102.7,1.05,1.05,0,0,0,116.8,102.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.02,scaleY:1.02},0).wait(1).to({scaleX:1.04,scaleY:1.04},0).wait(1).to({scaleX:1.05,scaleY:1.05},0).to({_off:true},1).to({_off:false,scaleX:1,scaleY:1},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({_off:true,scaleX:1,scaleY:1},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,4.1,224.3,197.3);


(lib.ico01_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0BEC5").s().p("AhvDTQg1gtgXhJQgHgHgKgXIgEgJQgIgRACgRQADgQALgIIAAgCQAAh2Afg2QAthOB8AAQB7gBAuBQQAfA2AAB0IAAACQAMAHACARQADARgIARIgEAJQgJAWgIAHQgWBJg0AvQg0Aug9AAIgBAAQg7AAg0gugAi1APIgBAAQgEACgBAIQgBAIAFAJIAEALIAKAUQAFACACAGQATBCAuAqQAuAqA0gBQA1gBAtgpQAugqAShCQABgFAFgDQAFgFAFgQIAFgKQAEgIgBgJQAAgIgFgCIAAAAQgGgCgCgGIgmALIgBAAQgFABgCgFIgNgdQgUAGggAAQgtAAg8gKQgqgHgegIIgUAtQgDAFgFgBIgggFQgDAFgEABg");
	this.shape.setTransform(106.9,131.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B0BEC5").s().p("AknAYIAAgvIJOAAIAAAvg");
	this.shape_1.setTransform(107.1,208.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B0BEC5").s().p("AjCBxIAAjhIGFAAIAADhg");
	this.shape_2.setTransform(107.8,192.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B0BEC5").s().p("AAwD8IAAj8IgbgaIjTAAIB+jhIBbARQATAEAOANQANANAFASIBvFlQAIAfgUAZQgTAZggAAg");
	this.shape_3.setTransform(127.9,178.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B0BEC5").s().p("Ah8D9QggAAgUgaQgUgZAIgfIBvllQAFgSANgNQAOgMASgEIBcgTIB+DiIjEAAIgbAaIAAD9g");
	this.shape_4.setTransform(86.2,178.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgvAeQgJgTAAg0IgBgJIATAAIgBAWQAAAXADAMQADAYAIAAQAEAAACgGQAFgLACgOQAFAFAHAHQgIAngRAAQgOAAgIgVgAAggCQgHgSgOgQIAPgHQAaAfAGAqIgRAGQgCgVgHgRg");
	this.shape_5.setTransform(137.1,57.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgRA2QgIgFAAgMQAAgKAIgHQAJgGALAAIANABIAAgdIARABQgCAHAAAGIABATQAMAFAKAIIAFADIACACIgHAQQgHgIgPgKIABADQAAAJgHAGQgGAIgRAAQgMAAgIgHgAgFAeQgEADAAAEQAAAJAMAAQAOAAAAgLIAAgGQgHgCgGAAQgFABgEACgAg9AhQAHgJAHgOQAHgNAGgSIgJABIgNgBIAAgQQAIABALABIAHgBQAEgQAAgIIASABIgFAXQAMgBAIgEIABAQIgZAEQgEAQgLAWIgNAZgAAOgdIAIgOQAaALAOAIIgIAPQgRgMgXgIg");
	this.shape_6.setTransform(123.3,56.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("Ag/A1QAHgJAIgSQAIgQAFgVIgZAEIgBgQQAOAAAPgDIAFgcIAAgCIASABIgGAcIAJgBQAMABAHAHQAGAHAAAQQAAAmgLANQgFAGgIAAQgKAAgMgEIAAgGIgBgMQAMAGAIgBQAGAAACgJQACgNAAgTQAAgIgCgDQgBgEgIABIgJAAQgEANgFAPQgEAQgMAYIgCAEIgBACgAAkgFQgFgLgFgGIAPgHQAQAVAGAYIgQAIQgDgRgIgMgAAUgwIALgGQAHAHAGALIgLAGQgHgMgGgGgAAkg4IAKgFQAJAIAFAJIgLAGQgGgKgHgIg");
	this.shape_7.setTransform(109.8,56.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AADAyQAOgGAKgLQgFgIgGgQIALgFQAFANADAFQAGgKACgJIgSAAIgKABIAAgNIALABIARAAIAJgBIAHAIIgCAEQgFASgIALQAIAJAMAGQgEAHgDAHQgMgHgKgLQgKANgNAGQgDgGgGgGgAgUA9IABgPIgBhsIAlAAIgBAuIgWAAIAAAOIAIAAIAKAAIAAAMIgKAAIgIAAIAAAOIAJAAIALgBIAAAPIgKgBIgKAAIABAYgAgGgdIAJAAIAAgSIgJAAgAg/A0IAAhuIAlAAIAABpIgNAAIAAgHIgLAAIAAAMgAgxAaIAKAAIAAgcIgKAAgAgxgPIAKAAIAAgeIgKAAgAAVgeIAJAAIANAAIAAgRIgNAAIgKAAIAAgPIAlAAIAAAtIgaAAIgKABg");
	this.shape_8.setTransform(96.2,57.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgWAzQgJgHAAgJQAAgIAHgGQAHgFALgBQANAAAIAMQAEAEADAJQARgGAAgPQgBgIgHgFQgIgFgMAAQgdAAgbAYIgKgQQAFgBAQgJQAXgTAQgSIADgCIgBAAIgsADIgBgRIARAAQAVABAUgCIAJgCIAIAMQgCACgFAEIgWAUQgFAFgIAGIgHAEIABAAQAOgGANAAQATAAAKAIQALAHAAAOQgBAVgSAKQgNAIgVAAQgSAAgHgHgAgPAjQAAAJAPAAIAHgBQgEgOgKAAQgIAAAAAGg");
	this.shape_9.setTransform(82.3,57.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AAHBBIABgRIAAhNIgDAAQgHATgOANQgDgEgHgGQAPgRAJgTQACgLACgKIAQAFIgGARIA1gBIAAAPIgqgBIAAASIAlgBIAAAOIglgBIAAASIAlgBIAAAPIglgBIAAAQQAAAOABADgAgsBBIABgRIAAg2IgNANQgDgHgFgHQAQgOALgZQAFgMABgGIAQAGIgEAIIgJAVIABBeg");
	this.shape_10.setTransform(68.9,57);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgUA3QgKgGAAgMQAAgJAGgHQAJgLATgJQgBgFgGAAQgMAAgQAMIgNANIgMgNQAFgDAHgHQALgNAGgLIABgCIgaAAIAAgQQAIACAZAAQAFgKAAgIIARACIgEANIgBADIAHgBQAZgCALgDIABAQIgLABQgNACgbABQgFALgIAIIAAAAIADgCQAIgGALAAQAPAAAEAOIAVgHIALgEIAGAOIgPAEIgVAHIAAABIAAALIAAAFIAAAIIgQAAIABgUIgMAIQgHAFAAAGQAAAKAWAAQAaAAAPgGIABATIgGAAQgRADgTAAQgSAAgLgGg");
	this.shape_11.setTransform(55.4,56.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgoBAIABgPIAAgiQgIAUgKALQgBgIgGgGQAIgIAIgNIAHgOIgUABIAAgPIAWABIAAgiIgBgNIAQAAIAAAvIARgBIAAAPIgLgBIgFAAQAIAMAKAHIgEAIIArgJIAAg+IgBgQIARAAIAABLIALgEIAEAQIgOADIgBAAIAAAlIgRAAIABgRIAAgRIgdAHIgLAEIgEgPIgBAEQgIgIgHgLIACAnIABAOgAgFgJIAIgKQAOAKALAJIgKALQgNgLgKgJgAgXgaQAGgNADgRIAMAFQgEAPgHAQgAg+gyIAMgGQAGARADAOIgNAFQgCgSgGgMgAgBgrIAIgLQAOAKALALIgKALQgJgKgOgLg");
	this.shape_12.setTransform(42.1,57.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AAJAxIAIgGIgkAAIAIAGQgSALgaAFQgEgHgFgGQAagCAMgHIgVAAIAAg2IAWABIgGgJIgaALIgGgPQAQgDASgJIAFAMIgFADQAOgCAHgEQAKgFADgLIgMAAIgNANQgEgHgGgDQASgLAEgOIANACIgFAJIApAAIALgBIAIAHIgCAEQgHAKgGAFIgNgFQAFgDAEgGIgVAAQAHAWAmACQgFAFgBAIIgOgDIABAzIgWAAQAQAHAXACQgEAFgEAIQgbgEgTgMgAgfAgIA+AAIAAgGIg+AAgAgfARIA+AAIAAgFIg+AAgAgfADIA+AAIAAgDIg+AAgAAAgRQgGAEgIADIAyAAQgPgHgIgMQgGAIgHAEgAg7gzIAJgLQANAHAJAHIgJALQgKgIgMgGg");
	this.shape_13.setTransform(28.1,57);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgwAeQgIgTgBg0IAAgJIATAAIgBAWQAAAXACAMQAFAYAHAAQADAAACgGQAGgLACgOQAFAFAHAHQgIAngRAAQgOAAgJgVgAAfgCQgGgSgNgQIAPgHQAZAfAGAqIgSAGQgBgVgIgRg");
	this.shape_14.setTransform(198.4,28.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AgRA3QgIgHAAgLQAAgKAIgHQAJgGALgBIANACIAAgdIARABQgCAHAAAGIABATQAMAGAKAGIAFAFIACABIgHAQQgHgJgPgIIABACQAAAJgHAHQgGAHgRAAQgMAAgIgGgAgJAlQAAAJAMAAQAOAAAAgLIAAgGQgHgBgGAAQgNAAAAAJgAg9AgQAHgIAHgOQAHgNAGgSIgWAAIAAgQQAIACALAAIAHgBQAEgPAAgJIASABIgFAXQAMgCAIgDIABARIgZADQgEAQgLAXIgNAXgAAOgdIAIgNQAaAKAOAIIgIAPQgRgMgXgIg");
	this.shape_15.setTransform(184.6,27.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgoA9QABgGAAgRIAAgTIgRAUIgIgRQAFgDAEgEIAQgPIABgVIgWADIgBgQIAXAAIAAgaIASABIgCAXIACAAIAFAFIgEAFIgCACIgCACIAAAIIAAADIAAAAQAFgFAMgJQAPgOANAAQAIAAAGAFQAFAFAAAJQAAAGgDAOIgGAfQAAAHAGAAQAFAAAEgIQAFgGAEgJQAEAJAFAHQgFAJgFAFQgKALgLgBQgGAAgGgDQgHgFAAgNQAAgJAGgZIADgQQAAgGgGAAQgGAAgLAIQgPAMgJAJIABA2g");
	this.shape_16.setTransform(171.1,28);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgjA2QgBgMgCgGQAWAHAQAAQANAAAJgFQAKgGAAgJQAAgHgHgEQgGgEgLAAQgSAAgPAKIgGAGIgSAAIAHgwIABgIIARABIgGAhIgBAEIABAAQAGgGAMgBQALgEALAAQASAAALAGQALAIAAAOQAAAQgPALQgNAJgWAAQgPAAgUgFgAgegsIAIgOQAHAEAPAFQARAFAMABIgGARQgdgHgYgLg");
	this.shape_17.setTransform(158.1,27.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AAhA0QgTgBgOgIQgSgMAAgWQAAgPAOgPQAFgIAMgHQgNACggADQgPABgIACIgBgTIAcAAIBEgEIAQgCIABASIgDAAQgOAAgNAIQgbAOAAAVQAAASARAFQAMAEAJgBIADAAIgDATg");
	this.shape_18.setTransform(145.3,28.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AghA0QgOgKAAgaIABhJIATAAIgBATIgCAxQABARADAGQAFAHAOAAQAWAAAJgYQAEgJADgMQAHAEAKAFQgIAagJAJQgPASgZAAQgOAAgKgGg");
	this.shape_19.setTransform(134,28);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AAOA+QgBgJgEgHQALACAGAAIAHAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBIAAhBIgfABIAAgPIAfAAIgBgbIARAAIgBAbIAOAAIAAAPIgDAAIgLgBIAABCQAAAJgCADQgFAFgMAAIgRgBgAhAAxQASgNALgVQgMgOgLgJIAKgLIAUATQAEgMABgPIgaAAIgNABIAAgQIAaABIAAgVIAQAAIAAAVIAUgBIAAAPIgIAAQgBAUgJAUIASAbIgJAMIgQgYQgMATgQAQQgFgIgGgGgAgBgFIAKgGQAMAOAIAQIgNAIQgJgVgIgLg");
	this.shape_20.setTransform(120.2,28);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AgBA9QgFgCAAgGIAAg1IgBgLIAOAAIAAA3QAAABAAABQAAAAAAABQAAAAABABQAAAAAAAAIAIABQAIAAACgEQABgDAAgTQAKAEAFABQgBAZgEAFQgFAGgQAAQgOAAgDgDgAhBA0QAHgLADgNQADgQAAgqIgBgTIAyAAIAAgOIAOAAIAAAOIA1AAIAAAPIgRgBIguAAQATALAQANIgLALQgOgNgUgMIAJgKIglAAQgBAsgCATQgDAUgJAQQgFgHgIgFgAgnAuQAGgMACgLQACgKABgPIAPACQgDAggIAXgAAjABIANgEQANAaAFAWIgPAHQgFgcgLgXg");
	this.shape_21.setTransform(106.2,27.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("Ag5BAIAAguIAiABIAKgBIAAAtIgOAAIAAgGIgQAAIAAAHgAgrAtIAQAAIAAgPIgQAAgAAqBAIAAgHIgiAAIAAAHIgOAAIABgPIgBgqIAJABIAOAAIAAgRIgNAAIgNABIAAgQIAOABIAMAAIAAgRIgXADQgBgFgEgJQARAAATgEQATgEAIgEIAJANIgHABQgPAFgHABIAAAUIAPAAIAQgBIAAAQIgQgBIgPAAIAAARIAPAAIALgBIAAA5gAAIAsIAiAAIAAgXIgiAAgAgXALIgZAAIgJAAIAAgLIAJAAIAZAAIAJAAIAAALIgJAAgAgXgHIgZAAIgJABIAAgNIAJAAIAZAAIAJAAIAAANIgJgBgAgVgaIgpABIAAgPIAoABIALgBIAAAPIgKgBgAgZguIggABIAAgOIAgAAIALAAIAAAOg");
	this.shape_22.setTransform(92.3,28);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AgDA8QgGgCAAgHIAAgJIgaAAIAAAHIgQAAIAAgzIBjAAIAAAhQAHAEAIACQgBARgFAEQgFAEgfAAQgVAAgDgCgAAEAvIABACQADACARAAQAPAAAFgCQACgCAAgFIgrAAgAAEAfIAdAAIAAgHIgdAAgAgjAfIAaAAIAAgHIgaAAgAAEAOIAdAAIAAgHIgdAAgAgjAOIAaAAIAAgHIgaAAgAgJgFIAAgbIgmAAIAAAUIgPAAIABgLIAAgVIA0ABIAAgFIgsAAIAAgNIBoAAIAAANIgvAAIAAAFIA3gBIAAAgIgOAAIAAgUIgpAAIABAbgAAggGIgVAAIAAgJIAVAAIAHAAIAAAJgAgigGIgHAAIAAgJIAHAAIAUAAIAAAJgAAggTIgVAAIAAgJIAHAAIAVAAIAAAJgAgigTIgHAAIAAgJIATAAIAIAAIAAAJg");
	this.shape_23.setTransform(78.4,28.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AAhA0QgTgBgNgIQgTgLABgXQAAgQANgOQAEgIANgHQgMACghADQgQABgHACIgBgTIAcAAIBEgEIAQgCIABASIgCAAQgOAAgOAIQgbAOAAAVQAAASARAFQALAEAKgBIACAAIgCATg");
	this.shape_24.setTransform(64.8,28.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AAHAsQgIgKgagUQgMgJAAgHQAAgFAFgGIAMgKQATgOALgNQAHgHAEgFIAQANIgSAPQgLALgUAQQgFADAAACQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAKAIQAVASAWATIAEAEIgPAOQgEgGgOgNg");
	this.shape_25.setTransform(52.8,28.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AghA0QgOgJAAgbIAAhJIAUAAQgBAGgBANIgBAxQAAARAEAGQAEAHAPAAQAWAAAJgYQAFgLACgKQAIAEAJAFQgIAZgJAKQgQASgYAAQgPAAgJgGg");
	this.shape_26.setTransform(41.8,28);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgsBAIABgRIAAhfIgBgPIARAAIAAAeIAIgEQAEAMAEAPIgLAFQgCgPgDgKIAABegAABA5QgGgDAAgMIAAhBIgJABIAAgRIAcAAIgBgXIARAAIgBAXIAjAAIAAARIgQgBIgoAAIAAA+QABAEADAAQADABAOAAQATAAANgCIAAAQQgQACgUgBQgQABgIgDgAg/AAQAGgQAAgUIAMACQgBAVgGARg");
	this.shape_27.setTransform(27.9,28.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_28.setTransform(12.3,62.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F44336").s().p("AgJAyQgEgEAAgGIgLhIQgBgIAHgHQAHgGALAAQAMgBAHAIQAHAHgBAHIgLBIQAAAGgEAEQgEAFgGAAQgFAAgEgFg");
	this.shape_29.setTransform(12.3,54.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F44336").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAHAAAEAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape_30.setTransform(12.3,34.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F44336").s().p("AgJAyQgEgEAAgGIgLhHQgBgJAHgHQAHgGALAAQAMgBAHAIQAHAGgBAJIgLBHQAAAGgEAEQgEAFgGAAQgFAAgEgFg");
	this.shape_31.setTransform(12.3,26.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#B0BEC5").ss(1,1,1).p("AuSn9QhCAAgvAvQgvAwAABBIAAIRQAABCAvAvQAvAvBCAAIMRAAIB+CqICCiqIMUAAQBCAAAvgvQAvgvAAhCIAAoRQAAhBgvgwQgvgvhCAAg");
	this.shape_32.setTransform(107.5,51);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AiBFTIsRAAQhCAAguguQgwgvABhDIAAoPQgBhDAwgvQAuguBCAAIclAAQBCAAAuAuQAwAvAABDIAAIPQAABDgwAvQguAuhCAAIsUAAIiBCqg");
	this.shape_33.setTransform(107.5,51);

	this.instance = new lib.ico01_mov();
	this.instance.setTransform(108,97.5,1,1,0,0,0,116.8,102.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance}]},1).wait(1));

	// レイヤー 2
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("Aq/IWIAAwsIWAAAIAAQsg");
	this.shape_34.setTransform(105.5,156.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_34).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,217,212);


// stage content:
(lib.icon = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* クリックして Web ページに移動
		特定のシンボルインスタンス上でクリックすると、新しいブラウザーウィンドウに URL がロードされます。
		
		手順 :
		1. http://www.adobe.com を目的の URL アドレスに置き換えます。
		   二重引用符 ("") は付けたままにします。
		*/
		
		this.button_2.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
			window.open("#it01", "_self");
		}
		
		/* クリックして Web ページに移動
		特定のシンボルインスタンス上でクリックすると、新しいブラウザーウィンドウに URL がロードされます。
		
		手順 :
		1. http://www.adobe.com を目的の URL アドレスに置き換えます。
		   二重引用符 ("") は付けたままにします。
		*/
		
		this.button_3.addEventListener("click", fl_ClickToGoToWebPage_2);
		
		function fl_ClickToGoToWebPage_2() {
			window.open("#it02", "_self");
		}
		
		/* クリックして Web ページに移動
		特定のシンボルインスタンス上でクリックすると、新しいブラウザーウィンドウに URL がロードされます。
		
		手順 :
		1. http://www.adobe.com を目的の URL アドレスに置き換えます。
		   二重引用符 ("") は付けたままにします。
		*/
		
		this.button_4.addEventListener("click", fl_ClickToGoToWebPage_3);
		
		function fl_ClickToGoToWebPage_3() {
			window.open("#it03", "_self");
		}
		
		/* クリックして Web ページに移動
		特定のシンボルインスタンス上でクリックすると、新しいブラウザーウィンドウに URL がロードされます。
		
		手順 :
		1. http://www.adobe.com を目的の URL アドレスに置き換えます。
		   二重引用符 ("") は付けたままにします。
		*/
		
		this.button_5.addEventListener("click", fl_ClickToGoToWebPage_4);
		
		function fl_ClickToGoToWebPage_4() {
			window.open("#it04", "_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// レイヤー 3
	this.button_5 = new lib.ico04_btn();
	this.button_5.setTransform(764.9,18.2);
	new cjs.ButtonHelper(this.button_5, 0, 1, 1);

	this.button_4 = new lib.ico03_btn();
	this.button_4.setTransform(516.6,18.2);
	new cjs.ButtonHelper(this.button_4, 0, 1, 1);

	this.button_3 = new lib.ico02_btn();
	this.button_3.setTransform(268.3,18.2);
	new cjs.ButtonHelper(this.button_3, 0, 1, 1);

	this.button_2 = new lib.ico01_btn();
	this.button_2.setTransform(127.5,123.5,1,1,0,0,0,107.5,105.3);
	new cjs.ButtonHelper(this.button_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.button_2},{t:this.button_3},{t:this.button_4},{t:this.button_5}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(515.8,132,969.1,212.2);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;